packages:
  - 'packages/*'
  - 'services/*'
  - 'apps/*'
allowBuilds:
  nx: set this to true or false
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - nx
  - prisma
  - sharp
