packages:
  - 'packages/*'
  - 'services/*'
  - 'apps/*'
allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  nx: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
onlyBuiltDependencies: '@nestjs/core'
