import { BaseSyncService, SyncConfig } from './base-sync-service';
import { EmergencyContactSchema } from '@egypt/shared-schemas';
import { DataSource } from '@egypt/shared-types';
import { z } from 'zod';

type EmergencyType = 'police' | 'ambulance' | 'fire' | 'civil_defense' | 'hospital' | 'emergency';

interface EmergencyRecord {
  nameAr: string;
  nameEn: string;
  type: EmergencyType;
  phone: string;
  hotline: string;
  governorate: string;
  city: string;
  latitude: number;
  longitude: number;
  isActive: boolean;
  isNational: boolean;
  category: 'national_hotline' | 'hospital' | 'ambulance_station';
}

const NATIONAL_EMERGENCY_NUMBERS: EmergencyRecord[] = [
  {
    nameAr: 'شرطة النجدة',
    nameEn: 'Police Emergency',
    type: 'police',
    phone: '122',
    hotline: '122',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'الإسعاف',
    nameEn: 'Ambulance Emergency',
    type: 'ambulance',
    phone: '123',
    hotline: '123',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'المطافئ (الدفاع المدني)',
    nameEn: 'Fire & Civil Defense',
    type: 'fire',
    phone: '180',
    hotline: '180',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'الدفاع المدني',
    nameEn: 'Civil Defense',
    type: 'civil_defense',
    phone: '180',
    hotline: '180',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'شرطة السياحة والآثار',
    nameEn: 'Tourist Police',
    type: 'police',
    phone: '126',
    hotline: '126',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'حوادث المرور',
    nameEn: 'Traffic Accidents',
    type: 'police',
    phone: '128',
    hotline: '128',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'الطوارئ الكهربائية',
    nameEn: 'Electricity Emergency',
    type: 'emergency',
    phone: '121',
    hotline: '121',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'طوارئ المياه',
    nameEn: 'Water Emergency',
    type: 'emergency',
    phone: '125',
    hotline: '125',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'طوارئ الغاز الطبيعي',
    nameEn: 'Natural Gas Emergency',
    type: 'emergency',
    phone: '129',
    hotline: '129',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'مركز السموم',
    nameEn: 'Poison Control Center',
    type: 'emergency',
    phone: '16000',
    hotline: '16000',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'خط نجدة الطفل',
    nameEn: 'Child Helpline',
    type: 'emergency',
    phone: '16000',
    hotline: '16000',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'خط الإساءة للمرأة',
    nameEn: 'Woman Abuse Hotline',
    type: 'emergency',
    phone: '15115',
    hotline: '15115',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'مكافحة الفساد',
    nameEn: 'Anti-Corruption Hotline',
    type: 'emergency',
    phone: '1551',
    hotline: '1551',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'حماية المستهلك',
    nameEn: 'Consumer Protection',
    type: 'emergency',
    phone: '19588',
    hotline: '19588',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'شكاوي سيارات الأجرة',
    nameEn: 'Taxi Complaints',
    type: 'emergency',
    phone: '16528',
    hotline: '16528',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
  {
    nameAr: 'شكاوي السياح',
    nameEn: 'Tourist Complaints',
    type: 'emergency',
    phone: '19654',
    hotline: '19654',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: true,
    category: 'national_hotline',
  },
];

const EMERGENCY_HOSPITALS: EmergencyRecord[] = [
  {
    nameAr: 'مستشفى قصر العيني التعليمي',
    nameEn: 'Kasr Al-Aini Teaching Hospital',
    type: 'hospital',
    phone: '0223648822',
    hotline: '0223648822',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0328,
    longitude: 31.2244,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى جامعة عين شمس',
    nameEn: 'Ain Shams University Hospital',
    type: 'hospital',
    phone: '0226822331',
    hotline: '0226822331',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0788,
    longitude: 31.2852,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'المستشفى الرئيسي لجامعة الإسكندرية',
    nameEn: 'Alexandria University Hospital',
    type: 'hospital',
    phone: '035931731',
    hotline: '035931731',
    governorate: 'Alexandria',
    city: 'Alexandria',
    latitude: 31.2011,
    longitude: 29.9125,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى جامعة المنصورة',
    nameEn: 'Mansoura University Hospital',
    type: 'hospital',
    phone: '0502202304',
    hotline: '0502202304',
    governorate: 'Dakahlia',
    city: 'Mansoura',
    latitude: 31.0442,
    longitude: 31.3523,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى جامعة أسيوط',
    nameEn: 'Assiut University Hospital',
    type: 'hospital',
    phone: '0882412365',
    hotline: '0882412365',
    governorate: 'Assiut',
    city: 'Assiut',
    latitude: 27.1846,
    longitude: 31.1737,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى جامعة طنطا',
    nameEn: 'Tanta University Hospital',
    type: 'hospital',
    phone: '0403311234',
    hotline: '0403311234',
    governorate: 'Gharbia',
    city: 'Tanta',
    latitude: 30.7917,
    longitude: 31.0017,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى جامعة الزقازيق',
    nameEn: 'Zagazig University Hospital',
    type: 'hospital',
    phone: '0552356789',
    hotline: '0552356789',
    governorate: 'Sharqia',
    city: 'Zagazig',
    latitude: 30.5877,
    longitude: 31.4920,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى معهد ناصر',
    nameEn: 'Nasser Institute Hospital',
    type: 'hospital',
    phone: '0222456789',
    hotline: '0222456789',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0549,
    longitude: 31.2280,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى الدمرداش',
    nameEn: 'Demerdash Hospital',
    type: 'hospital',
    phone: '0226734567',
    hotline: '0226734567',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0739,
    longitude: 31.2840,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى الساحل التعليمي',
    nameEn: 'El-Sahel Teaching Hospital',
    type: 'hospital',
    phone: '0224506789',
    hotline: '0224506789',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.1200,
    longitude: 31.2400,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى كليوباترا',
    nameEn: 'Cleopatra Hospital',
    type: 'hospital',
    phone: '0226899999',
    hotline: '0226899999',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0964,
    longitude: 31.3200,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى دار الفؤاد',
    nameEn: 'Dar El Fouad Hospital',
    type: 'hospital',
    phone: '0238555555',
    hotline: '0238555555',
    governorate: 'Giza',
    city: '6th of October',
    latitude: 29.9550,
    longitude: 30.9350,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى الأندلسية',
    nameEn: 'Andalusia Hospital',
    type: 'hospital',
    phone: '035451111',
    hotline: '035451111',
    governorate: 'Alexandria',
    city: 'Alexandria',
    latitude: 31.2320,
    longitude: 29.9540,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى سعودي جيرمن',
    nameEn: 'Saudi German Hospital',
    type: 'hospital',
    phone: '0226981111',
    hotline: '0226981111',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0740,
    longitude: 31.3454,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
  {
    nameAr: 'مستشفى النيل بدراوي',
    nameEn: 'Nile Badrawi Hospital',
    type: 'hospital',
    phone: '0227944444',
    hotline: '0227944444',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0346,
    longitude: 31.2138,
    isActive: true,
    isNational: false,
    category: 'hospital',
  },
];

const AMBULANCE_STATIONS: EmergencyRecord[] = [
  {
    nameAr: 'مرفق إسعاف القاهرة - الرئيسي',
    nameEn: 'Cairo Ambulance Station - Main',
    type: 'ambulance',
    phone: '123',
    hotline: '123',
    governorate: 'Cairo',
    city: 'Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف القاهرة - مدينة نصر',
    nameEn: 'Cairo Ambulance Station - Nasr City',
    type: 'ambulance',
    phone: '0224012345',
    hotline: '123',
    governorate: 'Cairo',
    city: 'Nasr City',
    latitude: 30.0600,
    longitude: 31.3300,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف الجيزة',
    nameEn: 'Giza Ambulance Station',
    type: 'ambulance',
    phone: '0235678901',
    hotline: '123',
    governorate: 'Giza',
    city: 'Giza',
    latitude: 30.0131,
    longitude: 31.2089,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف الإسكندرية',
    nameEn: 'Alexandria Ambulance Station',
    type: 'ambulance',
    phone: '034822200',
    hotline: '123',
    governorate: 'Alexandria',
    city: 'Alexandria',
    latitude: 31.2001,
    longitude: 29.9187,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف الدقهلية',
    nameEn: 'Dakahlia Ambulance Station',
    type: 'ambulance',
    phone: '0502345678',
    hotline: '123',
    governorate: 'Dakahlia',
    city: 'Mansoura',
    latitude: 31.0409,
    longitude: 31.3809,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف الشرقية',
    nameEn: 'Sharqia Ambulance Station',
    type: 'ambulance',
    phone: '0552356789',
    hotline: '123',
    governorate: 'Sharqia',
    city: 'Zagazig',
    latitude: 30.5877,
    longitude: 31.5020,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف الغربية',
    nameEn: 'Gharbia Ambulance Station',
    type: 'ambulance',
    phone: '0403321234',
    hotline: '123',
    governorate: 'Gharbia',
    city: 'Tanta',
    latitude: 30.7865,
    longitude: 31.0001,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف أسيوط',
    nameEn: 'Assiut Ambulance Station',
    type: 'ambulance',
    phone: '0882325678',
    hotline: '123',
    governorate: 'Assiut',
    city: 'Assiut',
    latitude: 27.1809,
    longitude: 31.1837,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف المنيا',
    nameEn: 'Minya Ambulance Station',
    type: 'ambulance',
    phone: '0862345678',
    hotline: '123',
    governorate: 'Minya',
    city: 'Minya',
    latitude: 28.1099,
    longitude: 30.7503,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
  {
    nameAr: 'مرفق إسعاف بورسعيد',
    nameEn: 'Port Said Ambulance Station',
    type: 'ambulance',
    phone: '0663345678',
    hotline: '123',
    governorate: 'Port Said',
    city: 'Port Said',
    latitude: 31.2653,
    longitude: 32.3019,
    isActive: true,
    isNational: false,
    category: 'ambulance_station',
  },
];

const ALL_RECORDS: EmergencyRecord[] = [
  ...NATIONAL_EMERGENCY_NUMBERS,
  ...EMERGENCY_HOSPITALS,
  ...AMBULANCE_STATIONS,
];

export class EmergencyCollector extends BaseSyncService<any> {
  readonly syncConfig: SyncConfig = {
    domain: 'emergency',
    tableName: 'emergencyContact',
    idField: 'id',
    matchFields: ['hotline', 'type', 'category'],
    trackedFields: ['nameAr', 'nameEn', 'hotline', 'phone', 'type', 'governorate', 'city', 'latitude', 'longitude', 'isActive', 'isNational', 'category'],
  };

  readonly schema = EmergencyContactSchema.extend({
    type: z.enum(['police', 'ambulance', 'fire', 'civil_defense', 'hospital', 'emergency']),
    phone: z.string(),
    governorate: z.string(),
    city: z.string(),
    isNational: z.boolean(),
    category: z.enum(['national_hotline', 'hospital', 'ambulance_station']),
    alternatePhone: z.string().optional(),
  });

  protected async fetchFromSource(source: DataSource): Promise<unknown[]> {
    const results: any[] = [];
    const errors: string[] = [];

    for (const record of ALL_RECORDS) {
      try {
        results.push({
          nameAr: record.nameAr,
          nameEn: record.nameEn,
          type: record.type,
          phone: record.phone,
          hotline: record.hotline,
          alternatePhone: undefined,
          governorate: record.governorate,
          city: record.city,
          latitude: record.latitude,
          longitude: record.longitude,
          isActive: record.isActive,
          isNational: record.isNational,
          category: record.category,
        });
        console.log(`[EmergencyCollector] Collected: ${record.nameEn} (${record.type})`);
      } catch (error: any) {
        errors.push(`Failed to collect ${record.nameEn}: ${error.message}`);
        console.error(`[EmergencyCollector] Error collecting ${record.nameEn}: ${error.message}`);
      }
    }

    if (errors.length > 0) {
      console.warn(`[EmergencyCollector] ${errors.length} errors during collection`);
    }

    return results;
  }
}
