import { BaseSyncService, SyncConfig } from './base-sync-service';
import { GovernmentOfficeSchema } from '@egypt/shared-schemas';
import { DataSource } from '@egypt/shared-types';

interface GovernmentOffice {
  nameAr: string;
  nameEn: string;
  code: string;
  type: 'passport' | 'civil_registry' | 'real_estate_registry' | 'tax' | 'social_insurance' | 'notary_public' | 'interior' | 'traffic';
  phone: string;
  email: string;
  governorate: string;
  city: string;
  street: string;
  latitude: number;
  longitude: number;
  workingHours: string;
  services: string[];
  sourceUrl: string;
  isActive: boolean;
}

const EGYPTIAN_GOVERNMENT_OFFICES: GovernmentOffice[] = [
  // ─── Passport Offices (جوازات السفر) ───
  {
    nameAr: 'مكتب جوازات القاهرة',
    nameEn: 'Cairo Passport Office',
    code: 'PAS-CAI-001',
    type: 'passport',
    phone: '02-27948000',
    email: 'cairo.passport@moi.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'ميدان العباسية، قسم الوايلي',
    latitude: 30.0689,
    longitude: 31.2758,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر', 'بدل فاقد جواز سفر', 'إضافة أطفال'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },
  {
    nameAr: 'مكتب جوازات الجيزة',
    nameEn: 'Giza Passport Office',
    code: 'PAS-GIZ-002',
    type: 'passport',
    phone: '02-35860000',
    email: 'giza.passport@moi.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع البحر الأعظم، بجوار محطة مترو الجيزة',
    latitude: 30.0081,
    longitude: 31.2090,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر', 'بدل فاقد جواز سفر'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },
  {
    nameAr: 'مكتب جوازات الإسكندرية',
    nameEn: 'Alexandria Passport Office',
    code: 'PAS-ALX-003',
    type: 'passport',
    phone: '03-4820000',
    email: 'alex.passport@moi.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع بورسعيد، محرم بك',
    latitude: 31.1904,
    longitude: 29.9042,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر', 'بدل فاقد جواز سفر'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },
  {
    nameAr: 'مكتب جوازات الغربية',
    nameEn: 'Gharbia Passport Office',
    code: 'PAS-GHB-004',
    type: 'passport',
    phone: '040-3335000',
    email: 'gharbia.passport@moi.gov.eg',
    governorate: 'Gharbia',
    city: 'Tanta',
    street: 'شارع الجيش، بجوار مبنى المحافظة',
    latitude: 30.7942,
    longitude: 31.0018,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },
  {
    nameAr: 'مكتب جوازات الدقهلية',
    nameEn: 'Dakahlia Passport Office',
    code: 'PAS-DKH-005',
    type: 'passport',
    phone: '050-2336000',
    email: 'dakahlia.passport@moi.gov.eg',
    governorate: 'Dakahlia',
    city: 'Mansoura',
    street: 'شارع الجمهورية، بجوار الإستاد الرياضي',
    latitude: 31.0445,
    longitude: 31.3815,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر', 'بدل فاقد'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },
  {
    nameAr: 'مكتب جوازات الشرقية',
    nameEn: 'Sharqia Passport Office',
    code: 'PAS-SHR-006',
    type: 'passport',
    phone: '055-2348000',
    email: 'sharqia.passport@moi.gov.eg',
    governorate: 'Sharqia',
    city: 'Zagazig',
    street: 'شارع طلبة عويضة، بجوار مبنى المحافظة',
    latitude: 30.5915,
    longitude: 31.5050,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },
  {
    nameAr: 'مكتب جوازات أسيوط',
    nameEn: 'Assiut Passport Office',
    code: 'PAS-AST-007',
    type: 'passport',
    phone: '088-2334000',
    email: 'assiut.passport@moi.gov.eg',
    governorate: 'Assiut',
    city: 'Assiut',
    street: 'شارع المطار، حي شرق',
    latitude: 27.1764,
    longitude: 31.1897,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },
  {
    nameAr: 'مكتب جوازات أسوان',
    nameEn: 'Aswan Passport Office',
    code: 'PAS-ASW-008',
    type: 'passport',
    phone: '097-2318000',
    email: 'aswan.passport@moi.gov.eg',
    governorate: 'Aswan',
    city: 'Aswan',
    street: 'شارع خالد بن الوليد، حي العقاد',
    latitude: 24.0875,
    longitude: 32.8994,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['إصدار جواز سفر', 'تجديد جواز سفر'],
    sourceUrl: 'https://www.moi.gov.eg/passports',
    isActive: true,
  },

  // ─── Civil Registry Offices (الأحوال المدنية) ───
  {
    nameAr: 'مكتب الأحوال المدنية بالقاهرة',
    nameEn: 'Cairo Civil Registry Office',
    code: 'CIV-CAI-001',
    type: 'civil_registry',
    phone: '02-27953000',
    email: 'cairo.civil@moi.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع رمسيس، بجوار محطة مصر',
    latitude: 30.0625,
    longitude: 31.2478,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['استخراج شهادة ميلاد', 'استخراج شهادة وفاة', 'قيد عائلة', 'إثبات شخصية', 'بطاقة رقم قومي'],
    sourceUrl: 'https://www.moi.gov.eg/civilregistry',
    isActive: true,
  },
  {
    nameAr: 'مكتب الأحوال المدنية بالإسكندرية',
    nameEn: 'Alexandria Civil Registry Office',
    code: 'CIV-ALX-002',
    type: 'civil_registry',
    phone: '03-4846000',
    email: 'alex.civil@moi.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع سعد زغلول، محطة الرمل',
    latitude: 31.2015,
    longitude: 29.9160,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['بطاقة رقم قومي', 'استخراج شهادة ميلاد', 'قيد عائلة', 'إثبات شخصية'],
    sourceUrl: 'https://www.moi.gov.eg/civilregistry',
    isActive: true,
  },
  {
    nameAr: 'مكتب الأحوال المدنية بالجيزة',
    nameEn: 'Giza Civil Registry Office',
    code: 'CIV-GIZ-003',
    type: 'civil_registry',
    phone: '02-35879000',
    email: 'giza.civil@moi.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع فيصل، بجوار مستشفى أم المصريين',
    latitude: 30.0155,
    longitude: 31.2200,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['بطاقة رقم قومي', 'شهادة ميلاد', 'شهادة وفاة', 'قيد عائلة'],
    sourceUrl: 'https://www.moi.gov.eg/civilregistry',
    isActive: true,
  },
  {
    nameAr: 'مكتب الأحوال المدنية ببورسعيد',
    nameEn: 'Port Said Civil Registry Office',
    code: 'CIV-PSD-004',
    type: 'civil_registry',
    phone: '066-3336000',
    email: 'portsaid.civil@moi.gov.eg',
    governorate: 'Port Said',
    city: 'Port Said',
    street: 'شارع 23 يوليو، حي الزهور',
    latitude: 31.2635,
    longitude: 32.3050,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['بطاقة رقم قومي', 'شهادة ميلاد', 'شهادة وفاة'],
    sourceUrl: 'https://www.moi.gov.eg/civilregistry',
    isActive: true,
  },
  {
    nameAr: 'مكتب الأحوال المدنية بالأقصر',
    nameEn: 'Luxor Civil Registry Office',
    code: 'CIV-LXR-005',
    type: 'civil_registry',
    phone: '095-2374000',
    email: 'luxor.civil@moi.gov.eg',
    governorate: 'Luxor',
    city: 'Luxor',
    street: 'شارع الكرنك، بجوار معبد الأقصر',
    latitude: 25.6835,
    longitude: 32.6460,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['بطاقة رقم قومي', 'شهادة ميلاد', 'قيد عائلة'],
    sourceUrl: 'https://www.moi.gov.eg/civilregistry',
    isActive: true,
  },
  {
    nameAr: 'مكتب الأحوال المدنية بالمنيا',
    nameEn: 'Minya Civil Registry Office',
    code: 'CIV-MIN-006',
    type: 'civil_registry',
    phone: '086-2365000',
    email: 'minya.civil@moi.gov.eg',
    governorate: 'Minya',
    city: 'Minya',
    street: 'شارع الجمهورية، حي وسط المدينة',
    latitude: 28.1085,
    longitude: 30.7500,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['بطاقة رقم قومي', 'شهادة ميلاد', 'شهادة وفاة'],
    sourceUrl: 'https://www.moi.gov.eg/civilregistry',
    isActive: true,
  },

  // ─── Real Estate Registry Offices (الشهر العقاري) ───
  {
    nameAr: 'مكتب الشهر العقاري بالقاهرة',
    nameEn: 'Cairo Real Estate Registry Office',
    code: 'RER-CAI-001',
    type: 'real_estate_registry',
    phone: '02-27927000',
    email: 'cairo.realestate@moj.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع الجمهورية، باب اللوق',
    latitude: 30.0490,
    longitude: 31.2410,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['تسجيل عقارات', 'شهر عقاري', 'توثيق محررات', 'رهن عقاري', 'تصديق على التوقيعات'],
    sourceUrl: 'https://www.mohrsr.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب الشهر العقاري بالإسكندرية',
    nameEn: 'Alexandria Real Estate Registry Office',
    code: 'RER-ALX-002',
    type: 'real_estate_registry',
    phone: '03-4835000',
    email: 'alex.realestate@moj.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع النبي دانيال، محطة الرمل',
    latitude: 31.1980,
    longitude: 29.9080,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['تسجيل عقارات', 'شهر عقاري', 'رهن عقاري', 'توثيق محررات'],
    sourceUrl: 'https://www.mohrsr.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب الشهر العقاري بالغربية',
    nameEn: 'Gharbia Real Estate Registry Office',
    code: 'RER-GHB-003',
    type: 'real_estate_registry',
    phone: '040-3318000',
    email: 'gharbia.realestate@moj.gov.eg',
    governorate: 'Gharbia',
    city: 'Tanta',
    street: 'شارع النحاس، وسط البلد',
    latitude: 30.7880,
    longitude: 31.0050,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['تسجيل عقارات', 'شهر عقاري', 'توثيق محررات'],
    sourceUrl: 'https://www.mohrsr.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب الشهر العقاري بالدقهلية',
    nameEn: 'Dakahlia Real Estate Registry Office',
    code: 'RER-DKH-004',
    type: 'real_estate_registry',
    phone: '050-2342000',
    email: 'dakahlia.realestate@moj.gov.eg',
    governorate: 'Dakahlia',
    city: 'Mansoura',
    street: 'شارع سعد زغلول، حي الجامعة',
    latitude: 31.0420,
    longitude: 31.3780,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['تسجيل عقارات', 'شهر عقاري', 'رهن عقاري'],
    sourceUrl: 'https://www.mohrsr.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب الشهر العقاري بأسيوط',
    nameEn: 'Assiut Real Estate Registry Office',
    code: 'RER-AST-005',
    type: 'real_estate_registry',
    phone: '088-2321000',
    email: 'assiut.realestate@moj.gov.eg',
    governorate: 'Assiut',
    city: 'Assiut',
    street: 'شارع الجمهورية، حي غرب',
    latitude: 27.1820,
    longitude: 31.1800,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['تسجيل عقارات', 'شهر عقاري', 'توثيق محررات'],
    sourceUrl: 'https://www.mohrsr.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب الشهر العقاري بسوهاج',
    nameEn: 'Sohag Real Estate Registry Office',
    code: 'RER-SHG-006',
    type: 'real_estate_registry',
    phone: '093-2325000',
    email: 'sohag.realestate@moj.gov.eg',
    governorate: 'Sohag',
    city: 'Sohag',
    street: 'شارع الجلاء، وسط المدينة',
    latitude: 26.5550,
    longitude: 31.6950,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['تسجيل عقارات', 'شهر عقاري'],
    sourceUrl: 'https://www.mohrsr.gov.eg',
    isActive: true,
  },

  // ─── Tax Authority Offices (مصلحة الضرائب) ───
  {
    nameAr: 'مصلحة الضرائب المصرية - القاهرة',
    nameEn: 'Egyptian Tax Authority - Cairo',
    code: 'TAX-CAI-001',
    type: 'tax',
    phone: '02-27953000',
    email: 'cairo.tax@eta.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع رمسيس، ميدان العباسية',
    latitude: 30.0690,
    longitude: 31.2780,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['الضريبة على الدخل', 'ضريبة القيمة المضافة', 'ضريبة الدمغة', 'تقديم إقرارات ضريبية', 'استعلام ضريبي'],
    sourceUrl: 'https://www.eta.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مصلحة الضرائب المصرية - الجيزة',
    nameEn: 'Egyptian Tax Authority - Giza',
    code: 'TAX-GIZ-002',
    type: 'tax',
    phone: '02-35881000',
    email: 'giza.tax@eta.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع البحر الأعظم، بجوار مجمع الجيزة',
    latitude: 30.0120,
    longitude: 31.2070,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['الضريبة على الدخل', 'ضريبة القيمة المضافة', 'تقديم إقرارات ضريبية'],
    sourceUrl: 'https://www.eta.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مصلحة الضرائب المصرية - الإسكندرية',
    nameEn: 'Egyptian Tax Authority - Alexandria',
    code: 'TAX-ALX-003',
    type: 'tax',
    phone: '03-4851000',
    email: 'alex.tax@eta.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع سعد زغلول، محطة الرمل',
    latitude: 31.2005,
    longitude: 29.9140,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['الضريبة على الدخل', 'ضريبة القيمة المضافة', 'ضريبة الدمغة', 'تقديم إقرارات'],
    sourceUrl: 'https://www.eta.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مصلحة الضرائب المصرية - الدقهلية',
    nameEn: 'Egyptian Tax Authority - Dakahlia',
    code: 'TAX-DKH-004',
    type: 'tax',
    phone: '050-2358000',
    email: 'dakahlia.tax@eta.gov.eg',
    governorate: 'Dakahlia',
    city: 'Mansoura',
    street: 'شارع الجيش، حي الجامعة',
    latitude: 31.0390,
    longitude: 31.3750,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['الضريبة على الدخل', 'ضريبة القيمة المضافة', 'تقديم إقرارات ضريبية'],
    sourceUrl: 'https://www.eta.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مصلحة الضرائب المصرية - الشرقية',
    nameEn: 'Egyptian Tax Authority - Sharqia',
    code: 'TAX-SHR-005',
    type: 'tax',
    phone: '055-2337000',
    email: 'sharqia.tax@eta.gov.eg',
    governorate: 'Sharqia',
    city: 'Zagazig',
    street: 'شارع فاروق، وسط المدينة',
    latitude: 30.5870,
    longitude: 31.5000,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['الضريبة على الدخل', 'ضريبة القيمة المضافة', 'تقديم إقرارات'],
    sourceUrl: 'https://www.eta.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مصلحة الضرائب المصرية - قنا',
    nameEn: 'Egyptian Tax Authority - Qena',
    code: 'TAX-QNA-006',
    type: 'tax',
    phone: '096-5326000',
    email: 'qena.tax@eta.gov.eg',
    governorate: 'Qena',
    city: 'Qena',
    street: 'شارع سعد زغلول، وسط البلد',
    latitude: 26.1620,
    longitude: 32.7270,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['الضريبة على الدخل', 'ضريبة القيمة المضافة'],
    sourceUrl: 'https://www.eta.gov.eg',
    isActive: true,
  },

  // ─── Social Insurance Offices ───
  {
    nameAr: 'مكتب التأمينات الاجتماعية بالقاهرة',
    nameEn: 'Cairo Social Insurance Office',
    code: 'SOC-CAI-001',
    type: 'social_insurance',
    phone: '02-27946000',
    email: 'cairo.social@nosi.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع رمسيس، ميدان العباسية',
    latitude: 30.0670,
    longitude: 31.2800,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['تسجيل تأميني', 'صرف معاشات', 'اشتراكات تأمينية', 'استعلام عن المعاش', 'بدل فاقد وثيقة تأمين'],
    sourceUrl: 'https://www.nosi.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب التأمينات الاجتماعية بالإسكندرية',
    nameEn: 'Alexandria Social Insurance Office',
    code: 'SOC-ALX-002',
    type: 'social_insurance',
    phone: '03-4828000',
    email: 'alex.social@nosi.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع بورسعيد، محرم بك',
    latitude: 31.1910,
    longitude: 29.9050,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['تسجيل تأميني', 'صرف معاشات', 'اشتراكات تأمينية', 'استعلام عن المعاش'],
    sourceUrl: 'https://www.nosi.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب التأمينات الاجتماعية بالغربية',
    nameEn: 'Gharbia Social Insurance Office',
    code: 'SOC-GHB-003',
    type: 'social_insurance',
    phone: '040-3326000',
    email: 'gharbia.social@nosi.gov.eg',
    governorate: 'Gharbia',
    city: 'Tanta',
    street: 'شارع مدحت، وسط البلد',
    latitude: 30.7900,
    longitude: 31.0030,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['تسجيل تأميني', 'صرف معاشات', 'اشتراكات تأمينية'],
    sourceUrl: 'https://www.nosi.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب التأمينات الاجتماعية بالمنيا',
    nameEn: 'Minya Social Insurance Office',
    code: 'SOC-MIN-004',
    type: 'social_insurance',
    phone: '086-2354000',
    email: 'minya.social@nosi.gov.eg',
    governorate: 'Minya',
    city: 'Minya',
    street: 'شارع طه حسين، حي وسط',
    latitude: 28.1060,
    longitude: 30.7520,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['تسجيل تأميني', 'صرف معاشات', 'استعلام عن المعاش'],
    sourceUrl: 'https://www.nosi.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مكتب التأمينات الاجتماعية بالسويس',
    nameEn: 'Suez Social Insurance Office',
    code: 'SOC-SUZ-005',
    type: 'social_insurance',
    phone: '062-3332000',
    email: 'suez.social@nosi.gov.eg',
    governorate: 'Suez',
    city: 'Suez',
    street: 'شارع الجيش، حي الأربعين',
    latitude: 29.9680,
    longitude: 32.5460,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['تسجيل تأميني', 'صرف معاشات', 'اشتراكات تأمينية'],
    sourceUrl: 'https://www.nosi.gov.eg',
    isActive: true,
  },

  // ─── Notary Public Offices (التوثيق) ───
  {
    nameAr: 'مكتب توثيق القاهرة',
    nameEn: 'Cairo Notary Public Office',
    code: 'NOT-CAI-001',
    type: 'notary_public',
    phone: '02-27960000',
    email: 'cairo.notary@moj.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع الجمهورية، باب اللوق',
    latitude: 30.0480,
    longitude: 31.2420,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['توثيق عقود', 'تصديق على توقيعات', 'وكالات', 'إقرارات', 'توثيق محررات رسمية'],
    sourceUrl: 'https://www.moj.gov.eg/notary',
    isActive: true,
  },
  {
    nameAr: 'مكتب توثيق الجيزة',
    nameEn: 'Giza Notary Public Office',
    code: 'NOT-GIZ-002',
    type: 'notary_public',
    phone: '02-35850000',
    email: 'giza.notary@moj.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع فيصل، بجوار مسجد الرشاد',
    latitude: 30.0170,
    longitude: 31.2180,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['توثيق عقود', 'تصديق على توقيعات', 'وكالات', 'إقرارات'],
    sourceUrl: 'https://www.moj.gov.eg/notary',
    isActive: true,
  },
  {
    nameAr: 'مكتب توثيق الإسكندرية',
    nameEn: 'Alexandria Notary Public Office',
    code: 'NOT-ALX-003',
    type: 'notary_public',
    phone: '03-4862000',
    email: 'alex.notary@moj.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع النبي دانيال، محطة الرمل',
    latitude: 31.1970,
    longitude: 29.9090,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['توثيق عقود', 'تصديق على توقيعات', 'وكالات', 'إقرارات', 'توثيق محررات رسمية'],
    sourceUrl: 'https://www.moj.gov.eg/notary',
    isActive: true,
  },
  {
    nameAr: 'مكتب توثيق دمياط',
    nameEn: 'Damietta Notary Public Office',
    code: 'NOT-DMT-004',
    type: 'notary_public',
    phone: '057-2326000',
    email: 'damietta.notary@moj.gov.eg',
    governorate: 'Damietta',
    city: 'Damietta',
    street: 'شارع أحمد عرابي، حي شرق',
    latitude: 31.4180,
    longitude: 31.8150,
    workingHours: '8:00 AM - 3:00 PM',
    services: ['توثيق عقود', 'تصديق على توقيعات', 'وكالات'],
    sourceUrl: 'https://www.moj.gov.eg/notary',
    isActive: true,
  },
  {
    nameAr: 'مكتب توثيق الفيوم',
    nameEn: 'Fayoum Notary Public Office',
    code: 'NOT-FYM-005',
    type: 'notary_public',
    phone: '084-6334000',
    email: 'fayoum.notary@moj.gov.eg',
    governorate: 'Fayoum',
    city: 'Fayoum',
    street: 'شارع الحواتم، وسط المدينة',
    latitude: 29.3060,
    longitude: 30.8440,
    workingHours: '8:00 AM - 2:00 PM',
    services: ['توثيق عقود', 'تصديق على توقيعات', 'وكالات', 'إقرارات'],
    sourceUrl: 'https://www.moj.gov.eg/notary',
    isActive: true,
  },

  // ─── Ministry of Interior Offices ───
  {
    nameAr: 'وزارة الداخلية - ديوان عام الوزارة',
    nameEn: 'Ministry of Interior - Headquarters',
    code: 'MOI-HQ-001',
    type: 'interior',
    phone: '02-27965000',
    email: 'info@moi.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'ميدان العباسية، قسم الوايلي',
    latitude: 30.0695,
    longitude: 31.2760,
    workingHours: '8:00 AM - 4:00 PM',
    services: ['خدمات الجنسية', 'تصاريح العمل', 'قسم التشريعات', 'الشكاوى والبلاغات', 'خدمة الجمهور'],
    sourceUrl: 'https://www.moi.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مديرية أمن الإسكندرية',
    nameEn: 'Alexandria Security Directorate',
    code: 'MOI-ALX-002',
    type: 'interior',
    phone: '03-4840000',
    email: 'alex.directorate@moi.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع بورسعيد، محرم بك',
    latitude: 31.1920,
    longitude: 29.9030,
    workingHours: '8:00 AM - 4:00 PM',
    services: ['إدارة البحث الجنائي', 'قسم المرور', 'تصاريح السلاح', 'خدمة الجمهور', 'الشكاوى'],
    sourceUrl: 'https://www.moi.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مديرية أمن الشرقية',
    nameEn: 'Sharqia Security Directorate',
    code: 'MOI-SHR-003',
    type: 'interior',
    phone: '055-2355000',
    email: 'sharqia.directorate@moi.gov.eg',
    governorate: 'Sharqia',
    city: 'Zagazig',
    street: 'شارع طلبة عويضة، بجوار مبنى المحافظة',
    latitude: 30.5900,
    longitude: 31.5060,
    workingHours: '8:00 AM - 4:00 PM',
    services: ['قسم المرور', 'تصاريح السلاح', 'خدمة الجمهور', 'الشكاوى'],
    sourceUrl: 'https://www.moi.gov.eg',
    isActive: true,
  },
  {
    nameAr: 'مديرية أمن البحيرة',
    nameEn: 'Beheira Security Directorate',
    code: 'MOI-BHR-004',
    type: 'interior',
    phone: '045-3326000',
    email: 'beheira.directorate@moi.gov.eg',
    governorate: 'Beheira',
    city: 'Damanhur',
    street: 'شارع سعد زغلول، وسط المدينة',
    latitude: 31.0420,
    longitude: 30.4660,
    workingHours: '8:00 AM - 4:00 PM',
    services: ['قسم المرور', 'خدمة الجمهور', 'الشكاوى', 'الأحوال المدنية'],
    sourceUrl: 'https://www.moi.gov.eg',
    isActive: true,
  },

  // ─── Traffic Departments (مرور) ───
  {
    nameAr: 'إدارة مرور القاهرة',
    nameEn: 'Cairo Traffic Department',
    code: 'TRF-CAI-001',
    type: 'traffic',
    phone: '02-27964000',
    email: 'cairo.traffic@moi.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع رمسيس، ميدان العباسية',
    latitude: 30.0680,
    longitude: 31.2775,
    workingHours: '7:00 AM - 8:00 PM',
    services: ['ترخيص مركبات', 'رخصة قيادة', 'فحص فني', 'نقل ملكية', 'بدل فاقد رخصة', 'تسجيل مركبات'],
    sourceUrl: 'https://www.moi.gov.eg/traffic',
    isActive: true,
  },
  {
    nameAr: 'إدارة مرور الجيزة',
    nameEn: 'Giza Traffic Department',
    code: 'TRF-GIZ-002',
    type: 'traffic',
    phone: '02-35842000',
    email: 'giza.traffic@moi.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع البحر الأعظم، بجوار مستشفى أم المصريين',
    latitude: 30.0110,
    longitude: 31.2060,
    workingHours: '7:00 AM - 8:00 PM',
    services: ['ترخيص مركبات', 'رخصة قيادة', 'فحص فني', 'نقل ملكية', 'تسجيل مركبات'],
    sourceUrl: 'https://www.moi.gov.eg/traffic',
    isActive: true,
  },
  {
    nameAr: 'إدارة مرور الإسكندرية',
    nameEn: 'Alexandria Traffic Department',
    code: 'TRF-ALX-003',
    type: 'traffic',
    phone: '03-4819000',
    email: 'alex.traffic@moi.gov.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع بورسعيد، محرم بك',
    latitude: 31.1930,
    longitude: 29.9020,
    workingHours: '7:00 AM - 8:00 PM',
    services: ['ترخيص مركبات', 'رخصة قيادة', 'فحص فني', 'نقل ملكية'],
    sourceUrl: 'https://www.moi.gov.eg/traffic',
    isActive: true,
  },
  {
    nameAr: 'إدارة مرور الغربية',
    nameEn: 'Gharbia Traffic Department',
    code: 'TRF-GHB-004',
    type: 'traffic',
    phone: '040-3305000',
    email: 'gharbia.traffic@moi.gov.eg',
    governorate: 'Gharbia',
    city: 'Tanta',
    street: 'شارع الجيش، بجوار مبنى المحافظة',
    latitude: 30.7950,
    longitude: 31.0020,
    workingHours: '7:00 AM - 6:00 PM',
    services: ['ترخيص مركبات', 'رخصة قيادة', 'فحص فني', 'نقل ملكية'],
    sourceUrl: 'https://www.moi.gov.eg/traffic',
    isActive: true,
  },
  {
    nameAr: 'إدارة مرور أسوان',
    nameEn: 'Aswan Traffic Department',
    code: 'TRF-ASW-005',
    type: 'traffic',
    phone: '097-2306000',
    email: 'aswan.traffic@moi.gov.eg',
    governorate: 'Aswan',
    city: 'Aswan',
    street: 'شارع خالد بن الوليد، حي العقاد',
    latitude: 24.0860,
    longitude: 32.9000,
    workingHours: '7:00 AM - 2:00 PM',
    services: ['ترخيص مركبات', 'رخصة قيادة', 'فحص فني'],
    sourceUrl: 'https://www.moi.gov.eg/traffic',
    isActive: true,
  },
  {
    nameAr: 'إدارة مرور القليوبية',
    nameEn: 'Qalyubia Traffic Department',
    code: 'TRF-KAL-006',
    type: 'traffic',
    phone: '013-3226000',
    email: 'qalyubia.traffic@moi.gov.eg',
    governorate: 'Qalyubia',
    city: 'Benha',
    street: 'شارع سعد زغلول، وسط المدينة',
    latitude: 30.4620,
    longitude: 31.1860,
    workingHours: '7:00 AM - 6:00 PM',
    services: ['ترخيص مركبات', 'رخصة قيادة', 'فحص فني', 'نقل ملكية'],
    sourceUrl: 'https://www.moi.gov.eg/traffic',
    isActive: true,
  },
];

export class GovernmentCollector extends BaseSyncService<any> {
  readonly syncConfig: SyncConfig = {
    domain: 'government',
    tableName: 'governmentOffice',
    idField: 'id',
    matchFields: ['code'],
    externalIdField: 'code',
    trackedFields: ['nameAr', 'nameEn', 'type', 'phone', 'email', 'latitude', 'longitude', 'street', 'workingHours', 'services', 'isActive'],
  };
  readonly schema = GovernmentOfficeSchema;

  protected async fetchFromSource(source: DataSource): Promise<unknown[]> {
    const results: any[] = [];
    const errors: string[] = [];

    for (const office of EGYPTIAN_GOVERNMENT_OFFICES) {
      try {
        const record = {
          nameAr: office.nameAr,
          nameEn: office.nameEn,
          code: office.code,
          type: office.type,
          phone: office.phone,
          email: office.email,
          governorate: office.governorate,
          city: office.city,
          street: office.street,
          latitude: office.latitude,
          longitude: office.longitude,
          workingHours: office.workingHours,
          services: office.services,
          sourceUrl: office.sourceUrl,
          isActive: office.isActive,
        };
        results.push(record);
        console.log(`[GovernmentCollector] Collected: ${office.nameAr} (${office.code})`);
      } catch (error: any) {
        errors.push(`Failed to collect ${office.nameAr}: ${error.message}`);
        console.error(`[GovernmentCollector] Error collecting ${office.nameAr}: ${error.message}`);
      }
    }

    if (errors.length > 0) {
      console.warn(`[GovernmentCollector] ${errors.length} errors during collection`);
    }

    return results;
  }
}
