import { BaseSyncService, SyncConfig } from './base-sync-service';
import { HospitalSchema } from '@egypt/shared-schemas';
import { DataSource } from '@egypt/shared-types';

interface EgyptianHospital {
  nameAr: string;
  nameEn: string;
  code: string;
  type: 'government' | 'private' | 'teaching' | 'specialized' | 'military';
  phone: string;
  email: string;
  website: string;
  governorate: string;
  city: string;
  street: string;
  latitude: number;
  longitude: number;
  emergency: boolean;
  ambulance: boolean;
  departments: string[];
  beds: number;
  isActive: boolean;
}

const EGYPTIAN_HOSPITALS: EgyptianHospital[] = [
  {
    nameAr: 'مستشفى قصر العيني التعليمي (القصر العيني)',
    nameEn: 'Kasr Al-Aini Teaching Hospital',
    code: 'KASR_ALAINI',
    type: 'teaching',
    phone: '0223648822',
    email: 'info@kasralainy.edu.eg',
    website: 'https://www.kasralainy.edu.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع قصر العيني - القاهرة',
    latitude: 30.0328,
    longitude: 31.2244,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 4800,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة عين شمس',
    nameEn: 'Ain Shams University Hospital',
    code: 'AINSHAMS',
    type: 'teaching',
    phone: '0226822331',
    email: 'info@med.asu.edu.eg',
    website: 'https://www.asu.edu.eg/medicine',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع رمسيس - العباسية - القاهرة',
    latitude: 30.0788,
    longitude: 31.2852,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'روماتيزم', 'سمعيات', 'تخاطب', 'علاج طبيعي', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 3200,
    isActive: true,
  },
  {
    nameAr: 'المستشفى الرئيسي لجامعة الإسكندرية',
    nameEn: 'Alexandria University Hospital',
    code: 'ALEX_UNI',
    type: 'teaching',
    phone: '035931731',
    email: 'info@alexmed.edu.eg',
    website: 'https://www.alexmed.edu.eg',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع الحريه - محطة الرمل - الإسكندرية',
    latitude: 31.2011,
    longitude: 29.9125,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي', 'سمعيات', 'علاج طبيعي'],
    beds: 2800,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة المنصورة',
    nameEn: 'Mansoura University Hospital',
    code: 'MANSOURA_UNI',
    type: 'teaching',
    phone: '0502202304',
    email: 'info@mu.edu.eg',
    website: 'https://www.mans.edu.eg/medicine',
    governorate: 'Dakahlia',
    city: 'Mansoura',
    street: 'شارع الجمهورية - المنصورة',
    latitude: 31.0442,
    longitude: 31.3523,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي', 'جراحة تجميل', 'علاج طبيعي'],
    beds: 3500,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة أسيوط',
    nameEn: 'Assiut University Hospital',
    code: 'ASSIUT_UNI',
    type: 'teaching',
    phone: '0882412365',
    email: 'info@aun.edu.eg',
    website: 'https://www.aun.edu.eg/medicine',
    governorate: 'Assiut',
    city: 'Assiut',
    street: 'شارع الجامعة - أسيوط',
    latitude: 27.1846,
    longitude: 31.1737,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي', 'حروق', 'مناظير'],
    beds: 2800,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة طنطا',
    nameEn: 'Tanta University Hospital',
    code: 'TANTA_UNI',
    type: 'teaching',
    phone: '0403311234',
    email: 'info@med.tanta.edu.eg',
    website: 'https://www.tanta.edu.eg/medicine',
    governorate: 'Gharbia',
    city: 'Tanta',
    street: 'شارع سعيد - طنطا',
    latitude: 30.7917,
    longitude: 31.0017,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 1800,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة الزقازيق',
    nameEn: 'Zagazig University Hospital',
    code: 'ZAGAZIG_UNI',
    type: 'teaching',
    phone: '0552356789',
    email: 'info@zu.edu.eg',
    website: 'https://www.zu.edu.eg/medicine',
    governorate: 'Sharqia',
    city: 'Zagazig',
    street: 'شارع جامعة الزقازيق - الزقازيق',
    latitude: 30.5877,
    longitude: 31.4920,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 1600,
    isActive: true,
  },
  {
    nameAr: 'مستشفى كفر الشيخ العام',
    nameEn: 'Kafr El Sheikh General Hospital',
    code: 'KAFR_SHEIKH_GEN',
    type: 'government',
    phone: '0473234567',
    email: 'kafr_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Kafr El Sheikh',
    city: 'Kafr El Sheikh',
    street: 'شارع الجيش - كفر الشيخ',
    latitude: 31.1110,
    longitude: 30.9386,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'باطنة', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 500,
    isActive: true,
  },
  {
    nameAr: 'مستشفى معهد ناصر',
    nameEn: 'Nasser Institute Hospital',
    code: 'NASSER_INST',
    type: 'specialized',
    phone: '0222456789',
    email: 'info@nasserinst.edu.eg',
    website: 'https://www.nasserinst.edu.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع القصر العيني - السيدة زينب - القاهرة',
    latitude: 30.0549,
    longitude: 31.2280,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'جراحة', 'أورام', 'كلى', 'مسالك بولية', 'أطفال', 'نساء وتوليد', 'عظام', 'مخ وأعصاب', 'عيون', 'أنف وأذن وحنجرة', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 1200,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الدمرداش',
    nameEn: 'Demerdash Hospital',
    code: 'DEMERDASH',
    type: 'teaching',
    phone: '0226734567',
    email: 'demerdash@med.asu.edu.eg',
    website: 'https://www.asu.edu.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع رمسيس - العباسية - القاهرة',
    latitude: 30.0739,
    longitude: 31.2840,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 1500,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الساحل التعليمي',
    nameEn: 'El-Sahel Teaching Hospital',
    code: 'SAHEL_TEACH',
    type: 'teaching',
    phone: '0224506789',
    email: 'sahel_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع الساحل - شبرا - القاهرة',
    latitude: 30.1200,
    longitude: 31.2400,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'رعاية مركزة'],
    beds: 600,
    isActive: true,
  },
  {
    nameAr: 'مستشفى العجوزة',
    nameEn: 'El-Agouza Hospital',
    code: 'AGOUZA',
    type: 'government',
    phone: '0233467890',
    email: 'agouza_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع التحرير - العجوزة - الجيزة',
    latitude: 30.0376,
    longitude: 31.2095,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'أمراض صدرية', 'رعاية مركزة'],
    beds: 400,
    isActive: true,
  },
  {
    nameAr: 'مستشفى إمبابة العام',
    nameEn: 'Imbaba General Hospital',
    code: 'IMBABA',
    type: 'government',
    phone: '0231467890',
    email: 'imbaba_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع السودان - إمبابة - الجيزة',
    latitude: 30.0800,
    longitude: 31.2100,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'جلدية', 'رعاية مركزة'],
    beds: 350,
    isActive: true,
  },
  {
    nameAr: 'مستشفى حلوان العام',
    nameEn: 'Helwan General Hospital',
    code: 'HELWAN_GEN',
    type: 'government',
    phone: '0225567890',
    email: 'helwan_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Cairo',
    city: 'Helwan',
    street: 'شارع النصر - حلوان - القاهرة',
    latitude: 29.8414,
    longitude: 31.3342,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'رعاية مركزة'],
    beds: 450,
    isActive: true,
  },
  {
    nameAr: 'مستشفى المعادي العسكري',
    nameEn: 'Maadi Military Hospital',
    code: 'MAADI_MIL',
    type: 'military',
    phone: '0225212345',
    email: 'maadi_mil@mod.gov.eg',
    website: 'https://www.mod.gov.eg',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع النصر - المعادي - القاهرة',
    latitude: 29.9614,
    longitude: 31.2558,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي', 'حروق'],
    beds: 1000,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الشرطة بالعجوزة',
    nameEn: 'Police Hospital - Agouza',
    code: 'POLICE_AGOUZA',
    type: 'specialized',
    phone: '0233367890',
    email: 'police_hospital@moi.gov.eg',
    website: 'https://www.moi.gov.eg',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع التحرير - العجوزة - الجيزة',
    latitude: 30.0388,
    longitude: 31.2035,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 800,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة بني سويف',
    nameEn: 'Beni Suef University Hospital',
    code: 'BENISUEF_UNI',
    type: 'teaching',
    phone: '0822334567',
    email: 'info@med.bsu.edu.eg',
    website: 'https://www.bsu.edu.eg',
    governorate: 'Beni Suef',
    city: 'Beni Suef',
    street: 'شارع جامعة بني سويف - بني سويف',
    latitude: 29.0744,
    longitude: 31.0978,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 900,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة المنيا',
    nameEn: 'Minia University Hospital',
    code: 'MINIA_UNI',
    type: 'teaching',
    phone: '0862345678',
    email: 'info@med.minia.edu.eg',
    website: 'https://www.minia.edu.eg',
    governorate: 'Minya',
    city: 'Minya',
    street: 'شارع جامعة المنيا - المنيا',
    latitude: 28.1099,
    longitude: 30.7503,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'كلى', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 1100,
    isActive: true,
  },
  {
    nameAr: 'مستشفى جامعة سوهاج',
    nameEn: 'Sohag University Hospital',
    code: 'SOHAG_UNI',
    type: 'teaching',
    phone: '0932367890',
    email: 'info@med.sohag.edu.eg',
    website: 'https://www.sohag.edu.eg',
    governorate: 'Sohag',
    city: 'Sohag',
    street: 'شارع جامعة سوهاج - سوهاج',
    latitude: 26.5569,
    longitude: 31.6948,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'كلى', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 1200,
    isActive: true,
  },
  {
    nameAr: 'مستشفى كليوباترا',
    nameEn: 'Cleopatra Hospital',
    code: 'CLEOPATRA',
    type: 'private',
    phone: '0226899999',
    email: 'info@cleopatra-shifa.com.eg',
    website: 'https://www.cleopatrahospital.com',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع الحجاز - مصر الجديدة - القاهرة',
    latitude: 30.0964,
    longitude: 31.3200,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'رعاية مركزة', 'غسيل كلوي', 'مناظير', 'جهاز هضمي'],
    beds: 350,
    isActive: true,
  },
  {
    nameAr: 'مستشفى دار الفؤاد',
    nameEn: 'Dar El Fouad Hospital',
    code: 'DAR_FOUAD',
    type: 'private',
    phone: '0238555555',
    email: 'info@darelfouad.com',
    website: 'https://www.darelfouad.com',
    governorate: 'Giza',
    city: '6th of October',
    street: 'حي المتميزين - مدينة 6 أكتوبر - الجيزة',
    latitude: 29.9550,
    longitude: 30.9350,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'جراحة', 'مخ وأعصاب', 'أورام', 'كلى', 'عظام', 'رعاية مركزة', 'غسيل كلوي', 'أطفال', 'نساء وتوليد', 'مسالك بولية', 'عيون', 'أنف وأذن وحنجرة', 'مناظير', 'جهاز هضمي'],
    beds: 280,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الأندلسية',
    nameEn: 'Andalusia Hospital',
    code: 'ANDALUSIA',
    type: 'private',
    phone: '035451111',
    email: 'info@andalusiaegypt.com',
    website: 'https://www.andalusiaegypt.com',
    governorate: 'Alexandria',
    city: 'Alexandria',
    street: 'شارع بورسعيد - محطة الرمل - الإسكندرية',
    latitude: 31.2320,
    longitude: 29.9540,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة'],
    beds: 200,
    isActive: true,
  },
  {
    nameAr: 'مستشفى السلام',
    nameEn: 'El-Salam Hospital',
    code: 'SALAM_HOSP',
    type: 'private',
    phone: '0226244444',
    email: 'info@elsalamhospital.com',
    website: 'https://www.elsalamhospital.com',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع عبد الحميد بدوي - مصر الجديدة - القاهرة',
    latitude: 30.0764,
    longitude: 31.3200,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 400,
    isActive: true,
  },
  {
    nameAr: 'مستشفى سعودي جيرمن',
    nameEn: 'Saudi German Hospital',
    code: 'SAUDI_GERMAN',
    type: 'private',
    phone: '0226981111',
    email: 'info@saudigermanegypt.com',
    website: 'https://www.sghcairo.com',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع الميرغني - مصر الجديدة - القاهرة',
    latitude: 30.0740,
    longitude: 31.3454,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'جلدية', 'أمراض صدرية', 'رعاية مركزة', 'غسيل كلوي', 'مناظير', 'جهاز هضمي'],
    beds: 320,
    isActive: true,
  },
  {
    nameAr: 'مستشفى النيل بدراوي',
    nameEn: 'Nile Badrawi Hospital',
    code: 'NILE_BADRAWI',
    type: 'private',
    phone: '0227944444',
    email: 'info@nile-badrawi.com',
    website: 'https://www.nile-badrawi.com',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع النيل - جاردن سيتي - القاهرة',
    latitude: 30.0346,
    longitude: 31.2138,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'أورام', 'كلى', 'مسالك بولية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 250,
    isActive: true,
  },
  {
    nameAr: 'مستشفى النزهة الدولي',
    nameEn: 'El-Nozha International Hospital',
    code: 'NOZHA_INT',
    type: 'private',
    phone: '0226944444',
    email: 'info@nozhahospital.com',
    website: 'https://www.nozhahospital.com',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع النزهة - مصر الجديدة - القاهرة',
    latitude: 30.1076,
    longitude: 31.3310,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة'],
    beds: 180,
    isActive: true,
  },
  {
    nameAr: 'مستشفى المقطم الدولي',
    nameEn: 'El-Mokattam International Hospital',
    code: 'MOKATTAM_INT',
    type: 'private',
    phone: '0225071111',
    email: 'info@mokattamhospital.com',
    website: 'https://www.mokattamhospital.com',
    governorate: 'Cairo',
    city: 'Cairo',
    street: 'شارع 9 - المقطم - القاهرة',
    latitude: 30.0050,
    longitude: 31.3030,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة'],
    beds: 150,
    isActive: true,
  },
  {
    nameAr: 'مستشفى دار الشفاء',
    nameEn: 'Dar Al Shefa Hospital',
    code: 'DAR_SHEFA',
    type: 'private',
    phone: '0233334567',
    email: 'info@daralshefa.com',
    website: 'https://www.daralshefa.com',
    governorate: 'Giza',
    city: 'Giza',
    street: 'شارع فيصل - الجيزة',
    latitude: 30.0220,
    longitude: 31.2155,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة'],
    beds: 120,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الشيخ زايد الخاص',
    nameEn: 'El-Sheikh Zayed Hospital',
    code: 'SHEIKH_ZAYED',
    type: 'private',
    phone: '0238601111',
    email: 'info@sheikhzayedhospital.com',
    website: 'https://www.sheikhzayedhospital.com',
    governorate: 'Giza',
    city: '6th of October',
    street: 'شارع جنة - الشيخ زايد - 6 أكتوبر',
    latitude: 30.0410,
    longitude: 30.9600,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة', 'مناظير'],
    beds: 200,
    isActive: true,
  },
  {
    nameAr: 'مستشفى شرم الشيخ الدولي',
    nameEn: 'Sharm El Sheikh International Hospital',
    code: 'SHARM_INT',
    type: 'government',
    phone: '0693662222',
    email: 'sharm_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'South Sinai',
    city: 'Sharm El Sheikh',
    street: 'شارع السلام - شرم الشيخ - جنوب سيناء',
    latitude: 27.9158,
    longitude: 34.3299,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'جلدية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 300,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الغردقة العام',
    nameEn: 'Hurghada General Hospital',
    code: 'HURGHADA_GEN',
    type: 'government',
    phone: '0653542222',
    email: 'hurghada_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Red Sea',
    city: 'Hurghada',
    street: 'شارع النصر - الغردقة - البحر الأحمر',
    latitude: 27.2574,
    longitude: 33.8116,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 350,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الأقصر الدولي',
    nameEn: 'Luxor International Hospital',
    code: 'LUXOR_INT',
    type: 'government',
    phone: '0952371111',
    email: 'luxor_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Luxor',
    city: 'Luxor',
    street: 'شارع الكورنيش - الأقصر',
    latitude: 25.6872,
    longitude: 32.6396,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'رعاية مركزة'],
    beds: 250,
    isActive: true,
  },
  {
    nameAr: 'مستشفى أسوان الجامعي',
    nameEn: 'Aswan University Hospital',
    code: 'ASWAN_UNI',
    type: 'teaching',
    phone: '0972311111',
    email: 'info@med.aswu.edu.eg',
    website: 'https://www.aswu.edu.eg',
    governorate: 'Aswan',
    city: 'Aswan',
    street: 'شارع السادات - أسوان',
    latitude: 24.0889,
    longitude: 32.8998,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'مخ وأعصاب', 'كلى', 'رعاية مركزة', 'غسيل كلوي'],
    beds: 800,
    isActive: true,
  },
  {
    nameAr: 'مستشفى بورسعيد العام',
    nameEn: 'Port Said General Hospital',
    code: 'PORTSAID_GEN',
    type: 'government',
    phone: '0663332222',
    email: 'portsaid_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Port Said',
    city: 'Port Said',
    street: 'شارع 23 يوليو - بورسعيد',
    latitude: 31.2653,
    longitude: 32.3019,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة'],
    beds: 400,
    isActive: true,
  },
  {
    nameAr: 'مستشفى المحلة العام',
    nameEn: 'El-Mahalla General Hospital',
    code: 'MAHALLA_GEN',
    type: 'government',
    phone: '0402245678',
    email: 'mahalla_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Gharbia',
    city: 'Tanta',
    street: 'شارع البحر - المحلة الكبرى - الغربية',
    latitude: 30.9740,
    longitude: 31.1650,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'جلدية', 'رعاية مركزة'],
    beds: 300,
    isActive: true,
  },
  {
    nameAr: 'مستشفى دمنهور العام',
    nameEn: 'Damanhur General Hospital',
    code: 'DAMANHUR_GEN',
    type: 'government',
    phone: '0453334567',
    email: 'damanhur_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Beheira',
    city: 'Damanhur',
    street: 'شارع الجمهورية - دمنهور - البحيرة',
    latitude: 31.0409,
    longitude: 30.4685,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'جلدية', 'رعاية مركزة'],
    beds: 350,
    isActive: true,
  },
  {
    nameAr: 'مستشفى الإسماعيلية العام',
    nameEn: 'Ismailia General Hospital',
    code: 'ISMAILIA_GEN',
    type: 'government',
    phone: '0643345678',
    email: 'ismailia_hospital@mohp.gov.eg',
    website: 'https://www.mohp.gov.eg',
    governorate: 'Ismailia',
    city: 'Ismailia',
    street: 'شارع محمد علي - الإسماعيلية',
    latitude: 30.6043,
    longitude: 32.2723,
    emergency: true,
    ambulance: true,
    departments: ['طوارئ', 'قلب', 'أطفال', 'نساء وتوليد', 'عظام', 'جراحة', 'باطنة', 'عيون', 'أنف وأذن وحنجرة', 'رعاية مركزة'],
    beds: 300,
    isActive: true,
  },
];

const EGYPTIAN_GOVERNORATES: Record<string, { nameAr: string; nameEn: string; lat: number; lng: number }> = {
  'Cairo': { nameAr: 'القاهرة', nameEn: 'Cairo', lat: 30.0444, lng: 31.2357 },
  'Giza': { nameAr: 'الجيزة', nameEn: 'Giza', lat: 30.0131, lng: 31.2089 },
  'Alexandria': { nameAr: 'الإسكندرية', nameEn: 'Alexandria', lat: 31.2001, lng: 29.9187 },
  'Dakahlia': { nameAr: 'الدقهلية', nameEn: 'Dakahlia', lat: 31.0413, lng: 31.3809 },
  'Sharqia': { nameAr: 'الشرقية', nameEn: 'Sharqia', lat: 30.6183, lng: 31.7241 },
  'Qalyubia': { nameAr: 'القليوبية', nameEn: 'Qalyubia', lat: 30.3292, lng: 31.2168 },
  'Gharbia': { nameAr: 'الغربية', nameEn: 'Gharbia', lat: 30.8754, lng: 31.0409 },
  'Monufia': { nameAr: 'المنوفية', nameEn: 'Monufia', lat: 30.4602, lng: 30.9350 },
  'Beheira': { nameAr: 'البحيرة', nameEn: 'Beheira', lat: 30.8481, lng: 30.6056 },
  'Port Said': { nameAr: 'بورسعيد', nameEn: 'Port Said', lat: 31.2653, lng: 32.3019 },
  'Ismailia': { nameAr: 'الإسماعيلية', nameEn: 'Ismailia', lat: 30.6043, lng: 32.2723 },
  'Suez': { nameAr: 'السويس', nameEn: 'Suez', lat: 29.9668, lng: 32.5498 },
  'Damietta': { nameAr: 'دمياط', nameEn: 'Damietta', lat: 31.4165, lng: 31.8133 },
  'Luxor': { nameAr: 'الأقصر', nameEn: 'Luxor', lat: 25.6872, lng: 32.6396 },
  'Aswan': { nameAr: 'أسوان', nameEn: 'Aswan', lat: 24.0889, lng: 32.8998 },
  'Minya': { nameAr: 'المنيا', nameEn: 'Minya', lat: 28.1099, lng: 30.7503 },
  'Sohag': { nameAr: 'سوهاج', nameEn: 'Sohag', lat: 26.5569, lng: 31.6948 },
  'Assiut': { nameAr: 'أسيوط', nameEn: 'Assiut', lat: 27.1809, lng: 31.1837 },
  'Beni Suef': { nameAr: 'بني سويف', nameEn: 'Beni Suef', lat: 29.0744, lng: 31.0978 },
  'Fayoum': { nameAr: 'الفيوم', nameEn: 'Fayoum', lat: 29.3084, lng: 30.8428 },
  'Qena': { nameAr: 'قنا', nameEn: 'Qena', lat: 26.1640, lng: 32.7268 },
  'Red Sea': { nameAr: 'البحر الأحمر', nameEn: 'Red Sea', lat: 27.2574, lng: 33.8116 },
  'New Valley': { nameAr: 'الوادي الجديد', nameEn: 'New Valley', lat: 24.5456, lng: 27.1731 },
  'Matrouh': { nameAr: 'مطروح', nameEn: 'Matrouh', lat: 31.3528, lng: 27.2373 },
  'North Sinai': { nameAr: 'شمال سيناء', nameEn: 'North Sinai', lat: 30.9995, lng: 33.5904 },
  'South Sinai': { nameAr: 'جنوب سيناء', nameEn: 'South Sinai', lat: 29.0000, lng: 33.5000 },
  'Kafr El Sheikh': { nameAr: 'كفر الشيخ', nameEn: 'Kafr El Sheikh', lat: 31.1110, lng: 30.9386 },
};

const EGYPTIAN_CITIES: Record<string, { nameAr: string; nameEn: string; governorate: string; lat: number; lng: number }> = {
  'Cairo': { nameAr: 'القاهرة', nameEn: 'Cairo', governorate: 'Cairo', lat: 30.0444, lng: 31.2357 },
  'Giza': { nameAr: 'الجيزة', nameEn: 'Giza', governorate: 'Giza', lat: 30.0131, lng: 31.2089 },
  'Alexandria': { nameAr: 'الإسكندرية', nameEn: 'Alexandria', governorate: 'Alexandria', lat: 31.2001, lng: 29.9187 },
  'Shubra El Kheima': { nameAr: 'شبرا الخيمة', nameEn: 'Shubra El Kheima', governorate: 'Qalyubia', lat: 30.1286, lng: 31.2422 },
  'Helwan': { nameAr: 'حلوان', nameEn: 'Helwan', governorate: 'Cairo', lat: 29.8414, lng: 31.3342 },
  'Mansoura': { nameAr: 'المنصورة', nameEn: 'Mansoura', governorate: 'Dakahlia', lat: 31.0409, lng: 31.3809 },
  'Tanta': { nameAr: 'طنطا', nameEn: 'Tanta', governorate: 'Gharbia', lat: 30.7865, lng: 31.0001 },
  'Zagazig': { nameAr: 'الزقازيق', nameEn: 'Zagazig', governorate: 'Sharqia', lat: 30.5877, lng: 31.5020 },
  'Port Said': { nameAr: 'بورسعيد', nameEn: 'Port Said', governorate: 'Port Said', lat: 31.2653, lng: 32.3019 },
  'Suez': { nameAr: 'السويس', nameEn: 'Suez', governorate: 'Suez', lat: 29.9668, lng: 32.5498 },
  'Luxor': { nameAr: 'الأقصر', nameEn: 'Luxor', governorate: 'Luxor', lat: 25.6872, lng: 32.6396 },
  'Aswan': { nameAr: 'أسوان', nameEn: 'Aswan', governorate: 'Aswan', lat: 24.0889, lng: 32.8998 },
  'Benha': { nameAr: 'بنها', nameEn: 'Benha', governorate: 'Qalyubia', lat: 30.4602, lng: 31.1840 },
  'Damietta': { nameAr: 'دمياط', nameEn: 'Damietta', governorate: 'Damietta', lat: 31.4165, lng: 31.8133 },
  'Ismailia': { nameAr: 'الإسماعيلية', nameEn: 'Ismailia', governorate: 'Ismailia', lat: 30.6043, lng: 32.2723 },
  'Hurghada': { nameAr: 'الغردقة', nameEn: 'Hurghada', governorate: 'Red Sea', lat: 27.2574, lng: 33.8116 },
  'Sharm El Sheikh': { nameAr: 'شرم الشيخ', nameEn: 'Sharm El Sheikh', governorate: 'South Sinai', lat: 27.9158, lng: 34.3299 },
  'Damanhur': { nameAr: 'دمنهور', nameEn: 'Damanhur', governorate: 'Beheira', lat: 31.0409, lng: 30.4685 },
  'Kafr El Sheikh': { nameAr: 'كفر الشيخ', nameEn: 'Kafr El Sheikh', governorate: 'Kafr El Sheikh', lat: 31.1110, lng: 30.9386 },
  'Minya': { nameAr: 'المنيا', nameEn: 'Minya', governorate: 'Minya', lat: 28.1099, lng: 30.7503 },
  'Sohag': { nameAr: 'سوهاج', nameEn: 'Sohag', governorate: 'Sohag', lat: 26.5569, lng: 31.6948 },
  'Assiut': { nameAr: 'أسيوط', nameEn: 'Assiut', governorate: 'Assiut', lat: 27.1809, lng: 31.1837 },
  'Qena': { nameAr: 'قنا', nameEn: 'Qena', governorate: 'Qena', lat: 26.1640, lng: 32.7268 },
  'Beni Suef': { nameAr: 'بني سويف', nameEn: 'Beni Suef', governorate: 'Beni Suef', lat: 29.0744, lng: 31.0978 },
  'Fayoum': { nameAr: 'الفيوم', nameEn: 'Fayoum', governorate: 'Fayoum', lat: 29.3084, lng: 30.8428 },
  'Mersa Matruh': { nameAr: 'مرسى مطروح', nameEn: 'Mersa Matruh', governorate: 'Matrouh', lat: 31.3528, lng: 27.2373 },
  '6th of October': { nameAr: '6 أكتوبر', nameEn: '6th of October', governorate: 'Giza', lat: 29.9369, lng: 30.9167 },
};

export class HospitalsCollector extends BaseSyncService<any> {
  readonly syncConfig: SyncConfig = {
    domain: 'hospitals',
    tableName: 'hospital',
    idField: 'id',
    matchFields: ['code'],
    trackedFields: ['nameAr', 'nameEn', 'phone', 'email', 'website', 'type', 'governorate', 'city', 'street', 'latitude', 'longitude', 'emergency', 'ambulance', 'departments', 'beds', 'isActive'],
  };
  readonly schema = HospitalSchema;

  protected async fetchFromSource(source: DataSource): Promise<unknown[]> {
    const results: any[] = [];
    const errors: string[] = [];

    for (const hospital of EGYPTIAN_HOSPITALS) {
      try {
        const record = {
          nameAr: hospital.nameAr,
          nameEn: hospital.nameEn,
          code: hospital.code,
          phone: hospital.phone,
          email: hospital.email,
          website: hospital.website,
          type: hospital.type,
          governorate: hospital.governorate,
          city: hospital.city,
          street: hospital.street,
          latitude: hospital.latitude,
          longitude: hospital.longitude,
          emergency: hospital.emergency,
          ambulance: hospital.ambulance,
          departments: hospital.departments,
          beds: hospital.beds,
          isActive: hospital.isActive,
        };
        results.push(record);
        console.log(`[HospitalsCollector] Collected: ${hospital.nameAr} (${hospital.code})`);
      } catch (error: any) {
        errors.push(`Failed to collect ${hospital.nameAr}: ${error.message}`);
        console.error(`[HospitalsCollector] Error collecting ${hospital.nameAr}: ${error.message}`);
      }
    }

    if (errors.length > 0) {
      console.warn(`[HospitalsCollector] ${errors.length} errors during collection`);
    }

    return results;
  }
}
