import { BaseSyncService, SyncConfig } from './base-sync-service';
import { DataSource } from '@egypt/shared-types';
import { z } from 'zod';

interface SupermarketBranch {
  nameAr: string;
  nameEn: string;
  brandName: string;
  type: 'hypermarket' | 'supermarket' | 'mini' | 'co-op';
  governorate: string;
  city: string;
  street: string;
  latitude: number;
  longitude: number;
  phone: string | string[];
  website: string;
  hasDelivery: boolean;
  hasOnlineOrdering: boolean;
  workingHours: string;
  isActive: boolean;
}

interface SupermarketChain {
  nameAr: string;
  nameEn: string;
  brandName: string;
  type: 'hypermarket' | 'supermarket' | 'mini' | 'co-op';
  website: string;
  hasDelivery: boolean;
  hasOnlineOrdering: boolean;
  branches: Omit<SupermarketBranch, 'brandName' | 'type' | 'website' | 'hasDelivery' | 'hasOnlineOrdering'>[];
}

const SupermarketSchema = z.object({
  nameAr: z.string(),
  nameEn: z.string(),
  brandName: z.string(),
  type: z.enum(['hypermarket', 'supermarket', 'mini', 'co-op']),
  governorate: z.string(),
  city: z.string(),
  street: z.string(),
  latitude: z.number().min(22).max(32),
  longitude: z.number().min(25).max(37),
  phone: z.union([z.string(), z.array(z.string())]),
  website: z.string(),
  hasDelivery: z.boolean(),
  hasOnlineOrdering: z.boolean(),
  workingHours: z.string(),
  isActive: z.boolean(),
});

const SUPERMARKET_CHAINS: SupermarketChain[] = [
  {
    nameAr: 'كارفور مصر',
    nameEn: 'Carrefour Egypt',
    brandName: 'Carrefour',
    type: 'hypermarket',
    website: 'https://www.carrefouregypt.com',
    hasDelivery: true,
    hasOnlineOrdering: true,
    branches: [
      {
        nameAr: 'كارفور سيتي ستارز',
        nameEn: 'Carrefour Citystars',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'سيتي ستارز، طريق النصر، مدينة نصر',
        latitude: 30.0582,
        longitude: 31.3286,
        phone: ['16141', '0224801470'],
        workingHours: '9:00 AM - 12:00 AM',
        isActive: true,
      },
      {
        nameAr: 'كارفور المعادي',
        nameEn: 'Carrefour Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 233، المعادي',
        latitude: 29.9576,
        longitude: 31.2578,
        phone: ['16141', '0225251340'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور الشيخ زايد',
        nameEn: 'Carrefour Sheikh Zayed',
        governorate: 'الجيزة',
        city: 'الشيخ زايد',
        street: 'مول مصر، طريق القاهرة الإسكندرية الصحراوي',
        latitude: 30.0193,
        longitude: 31.0112,
        phone: ['16141'],
        workingHours: '9:00 AM - 12:00 AM',
        isActive: true,
      },
      {
        nameAr: 'كارفور المقطم',
        nameEn: 'Carrefour Mokattam',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'مركز سيتي سنتر المقطم',
        latitude: 30.0054,
        longitude: 31.3081,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور كايرو فيستيفال',
        nameEn: 'Carrefour Cairo Festival City',
        governorate: 'القاهرة',
        city: 'القاهرة الجديدة',
        street: 'كايرو فيستيفال سيتي، طريق القاهرة السويس الصحراوي',
        latitude: 30.0119,
        longitude: 31.4347,
        phone: ['16141'],
        workingHours: '9:00 AM - 12:00 AM',
        isActive: true,
      },
      {
        nameAr: 'كارفور الإسكندرية سان ستيفانو',
        nameEn: 'Carrefour San Stefano Alexandria',
        governorate: 'الإسكندرية',
        city: 'الإسكندرية',
        street: 'سان ستيفانو جراند بلازا، طريق الجيش',
        latitude: 31.2390,
        longitude: 29.9537,
        phone: ['16141', '034690200'],
        workingHours: '9:00 AM - 12:00 AM',
        isActive: true,
      },
      {
        nameAr: 'كارفور دمنهور',
        nameEn: 'Carrefour Damanhur',
        governorate: 'البحيرة',
        city: 'دمنهور',
        street: 'طريق الإسكندرية القاهرة الزراعي، دمنهور',
        latitude: 31.0400,
        longitude: 30.4685,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور طنطا',
        nameEn: 'Carrefour Tanta',
        governorate: 'الغربية',
        city: 'طنطا',
        street: 'طريق طنطا القاهرة، طنطا',
        latitude: 30.7833,
        longitude: 31.0000,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور المنصورة',
        nameEn: 'Carrefour Mansoura',
        governorate: 'الدقهلية',
        city: 'المنصورة',
        street: 'طريق المنصورة، جمصة، المنصورة',
        latitude: 31.0409,
        longitude: 31.3809,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور أسيوط',
        nameEn: 'Carrefour Assiut',
        governorate: 'أسيوط',
        city: 'أسيوط',
        street: 'طريق أسيوط سوهاج، أسيوط',
        latitude: 27.1809,
        longitude: 31.1837,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور العبور',
        nameEn: 'Carrefour Obour',
        governorate: 'القليوبية',
        city: 'العبور',
        street: 'مدينة العبور، طريق بلبيس',
        latitude: 30.2072,
        longitude: 31.4899,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور العاشر من رمضان',
        nameEn: 'Carrefour 10th of Ramadan',
        governorate: 'الشرقية',
        city: 'العاشر من رمضان',
        street: 'مدينة العاشر من رمضان',
        latitude: 30.3105,
        longitude: 31.7482,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور 6 أكتوبر',
        nameEn: 'Carrefour 6th of October',
        governorate: 'الجيزة',
        city: '6 أكتوبر',
        street: 'مول العرب، مدينة 6 أكتوبر',
        latitude: 29.9369,
        longitude: 30.9167,
        phone: ['16141'],
        workingHours: '9:00 AM - 12:00 AM',
        isActive: true,
      },
      {
        nameAr: 'كارفور بورسعيد',
        nameEn: 'Carrefour Port Said',
        governorate: 'بورسعيد',
        city: 'بورسعيد',
        street: 'طريق بورسعيد، حي الزهور',
        latitude: 31.2653,
        longitude: 32.3019,
        phone: ['16141'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'كارفور الغردقة',
        nameEn: 'Carrefour Hurghada',
        governorate: 'البحر الأحمر',
        city: 'الغردقة',
        street: 'طريق المطار، الغردقة',
        latitude: 27.1962,
        longitude: 33.8315,
        phone: ['16141'],
        workingHours: '9:00 AM - 12:00 AM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'هايبر وان',
    nameEn: 'Hyper One',
    brandName: 'Hyper One',
    type: 'hypermarket',
    website: 'https://www.hyperone.com.eg',
    hasDelivery: true,
    hasOnlineOrdering: false,
    branches: [
      {
        nameAr: 'هايبر وان الدقي',
        nameEn: 'Hyper One Dokki',
        governorate: 'الجيزة',
        city: 'الدقي',
        street: 'شارع التحرير، الدقي',
        latitude: 30.0389,
        longitude: 31.2076,
        phone: ['0233367200', '0233367201'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان المهندسين',
        nameEn: 'Hyper One Mohandessin',
        governorate: 'الجيزة',
        city: 'المهندسين',
        street: 'شارع سوريا، المهندسين',
        latitude: 30.0667,
        longitude: 31.2026,
        phone: ['0233456789'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان مصر الجديدة',
        nameEn: 'Hyper One Heliopolis',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع الحجاز، مصر الجديدة',
        latitude: 30.0894,
        longitude: 31.3418,
        phone: ['0224156789'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان مدينة نصر',
        nameEn: 'Hyper One Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع عباس العقاد، مدينة نصر',
        latitude: 30.0567,
        longitude: 31.3302,
        phone: ['0224012345'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان حلوان',
        nameEn: 'Hyper One Helwan',
        governorate: 'القاهرة',
        city: 'حلوان',
        street: 'شارع أحمد حلمي، حلوان',
        latitude: 29.8414,
        longitude: 31.3342,
        phone: ['0225567890'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان المقطم',
        nameEn: 'Hyper One Mokattam',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 9، المقطم',
        latitude: 30.0033,
        longitude: 31.3061,
        phone: ['0225012345'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان فيصل',
        nameEn: 'Hyper One Faisal',
        governorate: 'الجيزة',
        city: 'الجيزة',
        street: 'شارع الهرم، فيصل',
        latitude: 30.0083,
        longitude: 31.2023,
        phone: ['0235678901'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان الإسكندرية',
        nameEn: 'Hyper One Alexandria',
        governorate: 'الإسكندرية',
        city: 'الإسكندرية',
        street: 'شارع قناة السويس، محطة الرمل',
        latitude: 31.2001,
        longitude: 29.9187,
        phone: ['034567890'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان شبرا',
        nameEn: 'Hyper One Shubra',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع شبرا، روض الفرج',
        latitude: 30.0810,
        longitude: 31.2448,
        phone: ['0223056789'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'هايبر وان المعادي',
        nameEn: 'Hyper One Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 233، المعادي',
        latitude: 29.9598,
        longitude: 31.2584,
        phone: ['0225198765'],
        workingHours: '9:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'ماركت مترو',
    nameEn: 'Metro Market',
    brandName: 'Metro',
    type: 'supermarket',
    website: 'https://www.metro-market.com',
    hasDelivery: true,
    hasOnlineOrdering: true,
    branches: [
      {
        nameAr: 'مترو ميدان سفير',
        nameEn: 'Metro Safir Square',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'ميدان سفير، المهندسين',
        latitude: 30.0633,
        longitude: 31.1986,
        phone: ['0233025432'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو الدقي',
        nameEn: 'Metro Dokki',
        governorate: 'الجيزة',
        city: 'الدقي',
        street: 'شارع عبد الرحمن الرافعي، الدقي',
        latitude: 30.0375,
        longitude: 31.2063,
        phone: ['0233360123'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو مدينة نصر',
        nameEn: 'Metro Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع حسن المأمون، مدينة نصر',
        latitude: 30.0591,
        longitude: 31.3341,
        phone: ['0224017890'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو مصر الجديدة',
        nameEn: 'Metro Heliopolis',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع الميرغني، مصر الجديدة',
        latitude: 30.0917,
        longitude: 31.3439,
        phone: ['0224198765'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو الإسكندرية',
        nameEn: 'Metro Alexandria',
        governorate: 'الإسكندرية',
        city: 'الإسكندرية',
        street: 'شارع جمال عبد الناصر، محطة الرمل',
        latitude: 31.1992,
        longitude: 29.9114,
        phone: ['034567123'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو المعادي',
        nameEn: 'Metro Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 9، المعادي',
        latitude: 29.9608,
        longitude: 31.2603,
        phone: ['0225176543'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو الزمالك',
        nameEn: 'Metro Zamalek',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع البرازيل، الزمالك',
        latitude: 30.0648,
        longitude: 31.2162,
        phone: ['0227381234'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو العجوزة',
        nameEn: 'Metro Agouza',
        governorate: 'الجيزة',
        city: 'العجوزة',
        street: 'شارع أحمد عرابي، العجوزة',
        latitude: 30.0530,
        longitude: 31.2093,
        phone: ['0233451098'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو الهرم',
        nameEn: 'Metro Haram',
        governorate: 'الجيزة',
        city: 'الجيزة',
        street: 'شارع الهرم، بجوار مستشفى الهرم',
        latitude: 29.9954,
        longitude: 31.1675,
        phone: ['0233865432'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'مترو الشيخ زايد',
        nameEn: 'Metro Sheikh Zayed',
        governorate: 'الجيزة',
        city: 'الشيخ زايد',
        street: 'الحي الأول، الشيخ زايد',
        latitude: 30.0220,
        longitude: 31.0169,
        phone: ['0238567890'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'محلات ألفا',
    nameEn: 'Alfa Market',
    brandName: 'آلفا',
    type: 'supermarket',
    website: 'https://www.alfamarket.com',
    hasDelivery: true,
    hasOnlineOrdering: false,
    branches: [
      {
        nameAr: 'ألفا ميدان التحرير',
        nameEn: 'Alfa Tahrir Square',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع قصر النيل، ميدان التحرير',
        latitude: 30.0478,
        longitude: 31.2356,
        phone: ['0223925432'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'ألفا المهندسين',
        nameEn: 'Alfa Mohandessin',
        governorate: 'الجيزة',
        city: 'المهندسين',
        street: 'شارع لبنان، المهندسين',
        latitude: 30.0693,
        longitude: 31.2019,
        phone: ['0233458765'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'ألفا المعادي',
        nameEn: 'Alfa Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 253، المعادي',
        latitude: 29.9588,
        longitude: 31.2554,
        phone: ['0225219876'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'ألفا مدينة نصر',
        nameEn: 'Alfa Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع مكرم عبيد، مدينة نصر',
        latitude: 30.0572,
        longitude: 31.3287,
        phone: ['0224056543'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'ألفا الطالبية',
        nameEn: 'Alfa Talbiya',
        governorate: 'الجيزة',
        city: 'الجيزة',
        street: 'شارع الطالبية، الهرم',
        latitude: 29.9803,
        longitude: 31.1985,
        phone: ['0233825432'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'ألفا شبرا',
        nameEn: 'Alfa Shubra',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع شبرا، شبرا',
        latitude: 30.0789,
        longitude: 31.2439,
        phone: ['0223054321'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'خير زمان',
    nameEn: 'Kheir Zaman',
    brandName: 'خير زمان',
    type: 'supermarket',
    website: 'https://www.kheirzaman.com',
    hasDelivery: true,
    hasOnlineOrdering: false,
    branches: [
      {
        nameAr: 'خير زمان مدينة نصر',
        nameEn: 'Kheir Zaman Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع عباس العقاد، مدينة نصر',
        latitude: 30.0589,
        longitude: 31.3280,
        phone: ['0224011111'],
        workingHours: '9:00 AM - 10:00 PM',
        isActive: true,
      },
      {
        nameAr: 'خير زمان المهندسين',
        nameEn: 'Kheir Zaman Mohandessin',
        governorate: 'الجيزة',
        city: 'المهندسين',
        street: 'شارع سوريا، المهندسين',
        latitude: 30.0678,
        longitude: 31.2010,
        phone: ['0233454321'],
        workingHours: '9:00 AM - 10:00 PM',
        isActive: true,
      },
      {
        nameAr: 'خير زمان المعادي',
        nameEn: 'Kheir Zaman Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 9، المعادي',
        latitude: 29.9620,
        longitude: 31.2611,
        phone: ['0225198765'],
        workingHours: '9:00 AM - 10:00 PM',
        isActive: true,
      },
      {
        nameAr: 'خير زمان مصر الجديدة',
        nameEn: 'Kheir Zaman Heliopolis',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع الحجاز، مصر الجديدة',
        latitude: 30.0888,
        longitude: 31.3425,
        phone: ['0224187654'],
        workingHours: '9:00 AM - 10:00 PM',
        isActive: true,
      },
      {
        nameAr: 'خير زمان الدقي',
        nameEn: 'Kheir Zaman Dokki',
        governorate: 'الجيزة',
        city: 'الدقي',
        street: 'شارع محي الدين أبو العز، الدقي',
        latitude: 30.0366,
        longitude: 31.2038,
        phone: ['0233312345'],
        workingHours: '9:00 AM - 10:00 PM',
        isActive: true,
      },
      {
        nameAr: 'خير زمان العجوزة',
        nameEn: 'Kheir Zaman Agouza',
        governorate: 'الجيزة',
        city: 'العجوزة',
        street: 'شارع أحمد عرابي، العجوزة',
        latitude: 30.0520,
        longitude: 31.2101,
        phone: ['0233412345'],
        workingHours: '9:00 AM - 10:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'ماركت أوسكار',
    nameEn: 'Oscar Market',
    brandName: 'Oscar',
    type: 'supermarket',
    website: 'https://www.oscarmarket.com',
    hasDelivery: true,
    hasOnlineOrdering: false,
    branches: [
      {
        nameAr: 'أوسكار المهندسين',
        nameEn: 'Oscar Mohandessin',
        governorate: 'الجيزة',
        city: 'المهندسين',
        street: 'شارع البطل أحمد عبد العزيز، المهندسين',
        latitude: 30.0660,
        longitude: 31.2047,
        phone: ['0233467890'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أوسكار الدقي',
        nameEn: 'Oscar Dokki',
        governorate: 'الجيزة',
        city: 'الدقي',
        street: 'شارع التحرير، الدقي',
        latitude: 30.0396,
        longitude: 31.2070,
        phone: ['0233345678'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أوسكار فيصل',
        nameEn: 'Oscar Faisal',
        governorate: 'الجيزة',
        city: 'الجيزة',
        street: 'شارع الهرم، فيصل',
        latitude: 30.0091,
        longitude: 31.2018,
        phone: ['0233876543'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أوسكار المعادي',
        nameEn: 'Oscar Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 233، المعادي',
        latitude: 29.9584,
        longitude: 31.2581,
        phone: ['0225234567'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أوسكار مدينة نصر',
        nameEn: 'Oscar Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع عباس العقاد، مدينة نصر',
        latitude: 30.0575,
        longitude: 31.3299,
        phone: ['0224023456'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أوسكار مصر الجديدة',
        nameEn: 'Oscar Heliopolis',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع الميرغني، مصر الجديدة',
        latitude: 30.0925,
        longitude: 31.3448,
        phone: ['0224178901'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'أبناء رجب',
    nameEn: 'Ragab Sons',
    brandName: 'Ragab Sons',
    type: 'supermarket',
    website: 'https://www.ragabsons.com',
    hasDelivery: true,
    hasOnlineOrdering: false,
    branches: [
      {
        nameAr: 'أبناء رجب المنصورة',
        nameEn: 'Ragab Sons Mansoura',
        governorate: 'الدقهلية',
        city: 'المنصورة',
        street: 'شارع سعد زغلول، المنصورة',
        latitude: 31.0400,
        longitude: 31.3800,
        phone: ['0502345678'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبناء رجب طنطا',
        nameEn: 'Ragab Sons Tanta',
        governorate: 'الغربية',
        city: 'طنطا',
        street: 'شارع الجيش، طنطا',
        latitude: 30.7865,
        longitude: 31.0001,
        phone: ['0403312345'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبناء رجب القاهرة',
        nameEn: 'Ragab Sons Cairo',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع الأزهر، الأزهر',
        latitude: 30.0466,
        longitude: 31.2624,
        phone: ['0225912345'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبناء رجب الإسكندرية',
        nameEn: 'Ragab Sons Alexandria',
        governorate: 'الإسكندرية',
        city: 'الإسكندرية',
        street: 'شارع سموحة، سموحة',
        latitude: 31.2156,
        longitude: 29.9501,
        phone: ['034561234'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبناء رجب دمنهور',
        nameEn: 'Ragab Sons Damanhur',
        governorate: 'البحيرة',
        city: 'دمنهور',
        street: 'شارع الجمهورية، دمنهور',
        latitude: 31.0412,
        longitude: 30.4692,
        phone: ['0453321234'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'أبو عوف',
    nameEn: 'Abou Auf',
    brandName: 'Abou Auf',
    type: 'supermarket',
    website: 'https://www.abouauf.com',
    hasDelivery: true,
    hasOnlineOrdering: true,
    branches: [
      {
        nameAr: 'أبو عوف الدقي',
        nameEn: 'Abou Auf Dokki',
        governorate: 'الجيزة',
        city: 'الدقي',
        street: 'شارع التحرير، الدقي',
        latitude: 30.0384,
        longitude: 31.2065,
        phone: ['0233378901'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبو عوف المهندسين',
        nameEn: 'Abou Auf Mohandessin',
        governorate: 'الجيزة',
        city: 'المهندسين',
        street: 'شارع لبنان، المهندسين',
        latitude: 30.0685,
        longitude: 31.2005,
        phone: ['0233478901'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبو عوف الزمالك',
        nameEn: 'Abou Auf Zamalek',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 26 يوليو، الزمالك',
        latitude: 30.0636,
        longitude: 31.2146,
        phone: ['0227367890'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبو عوف المعادي',
        nameEn: 'Abou Auf Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 233، المعادي',
        latitude: 29.9592,
        longitude: 31.2575,
        phone: ['0225245678'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'أبو عوف مدينة نصر',
        nameEn: 'Abou Auf Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع مكرم عبيد، مدينة نصر',
        latitude: 30.0580,
        longitude: 31.3282,
        phone: ['0224034567'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'سوبر ماركت العبد',
    nameEn: 'El-Abd Supermarket',
    brandName: 'El-Abd',
    type: 'supermarket',
    website: 'https://www.elabd.com.eg',
    hasDelivery: true,
    hasOnlineOrdering: false,
    branches: [
      {
        nameAr: 'العبد المهندسين',
        nameEn: 'El-Abd Mohandessin',
        governorate: 'الجيزة',
        city: 'المهندسين',
        street: 'شارع جامعة الدول العربية، المهندسين',
        latitude: 30.0640,
        longitude: 31.1995,
        phone: ['0233489012'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'العبد الدقي',
        nameEn: 'El-Abd Dokki',
        governorate: 'الجيزة',
        city: 'الدقي',
        street: 'شارع التحرير، الدقي',
        latitude: 30.0378,
        longitude: 31.2059,
        phone: ['0233389012'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'العبد مصر الجديدة',
        nameEn: 'El-Abd Heliopolis',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع الميرغني، مصر الجديدة',
        latitude: 30.0910,
        longitude: 31.3430,
        phone: ['0224190123'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'العبد مدينة نصر',
        nameEn: 'El-Abd Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع حسن المأمون، مدينة نصر',
        latitude: 30.0599,
        longitude: 31.3336,
        phone: ['0224045678'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'العبد الهرم',
        nameEn: 'El-Abd Haram',
        governorate: 'الجيزة',
        city: 'الجيزة',
        street: 'شارع الهرم، الهرم',
        latitude: 29.9959,
        longitude: 31.1682,
        phone: ['0233889012'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
  {
    nameAr: 'سعودي ماركت',
    nameEn: 'Seoudi Market',
    brandName: 'Seoudi',
    type: 'supermarket',
    website: 'https://www.seoudimarket.com',
    hasDelivery: true,
    hasOnlineOrdering: true,
    branches: [
      {
        nameAr: 'سعودي ماركت المهندسين',
        nameEn: 'Seoudi Market Mohandessin',
        governorate: 'الجيزة',
        city: 'المهندسين',
        street: 'شارع البطل أحمد عبد العزيز، المهندسين',
        latitude: 30.0655,
        longitude: 31.2050,
        phone: ['0233490123'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'سعودي ماركت الدقي',
        nameEn: 'Seoudi Market Dokki',
        governorate: 'الجيزة',
        city: 'الدقي',
        street: 'شارع سليمان جوهر، الدقي',
        latitude: 30.0381,
        longitude: 31.2048,
        phone: ['0233390123'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'سعودي ماركت الشيخ زايد',
        nameEn: 'Seoudi Market Sheikh Zayed',
        governorate: 'الجيزة',
        city: 'الشيخ زايد',
        street: 'الحي الثالث، الشيخ زايد',
        latitude: 30.0245,
        longitude: 31.0185,
        phone: ['0238578901'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'سعودي ماركت 6 أكتوبر',
        nameEn: 'Seoudi Market 6th of October',
        governorate: 'الجيزة',
        city: '6 أكتوبر',
        street: 'الحي السابع، 6 أكتوبر',
        latitude: 29.9402,
        longitude: 30.9183,
        phone: ['0238345678'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'سعودي ماركت المعادي',
        nameEn: 'Seoudi Market Maadi',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع 233، المعادي',
        latitude: 29.9580,
        longitude: 31.2570,
        phone: ['0225256789'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
      {
        nameAr: 'سعودي ماركت مدينة نصر',
        nameEn: 'Seoudi Market Nasr City',
        governorate: 'القاهرة',
        city: 'القاهرة',
        street: 'شارع الطيران، مدينة نصر',
        latitude: 30.0612,
        longitude: 31.3315,
        phone: ['0224067890'],
        workingHours: '8:00 AM - 11:00 PM',
        isActive: true,
      },
    ],
  },
];

export class SupermarketsCollector extends BaseSyncService<any> {
  readonly syncConfig: SyncConfig = {
    domain: 'supermarkets',
    tableName: 'supermarket',
    idField: 'id',
    matchFields: ['nameAr', 'governorate', 'street'],
    trackedFields: [
      'nameAr', 'nameEn', 'brandName', 'type', 'governorate', 'city', 'street',
      'latitude', 'longitude', 'phone', 'website', 'hasDelivery',
      'hasOnlineOrdering', 'workingHours', 'isActive',
    ],
  };
  readonly schema = SupermarketSchema;

  protected async fetchFromSource(source: DataSource): Promise<unknown[]> {
    const results: any[] = [];

    for (const chain of SUPERMARKET_CHAINS) {
      for (const branch of chain.branches) {
        try {
          const record = {
            nameAr: branch.nameAr,
            nameEn: branch.nameEn,
            brandName: chain.brandName,
            type: chain.type,
            governorate: branch.governorate,
            city: branch.city,
            street: branch.street,
            latitude: branch.latitude,
            longitude: branch.longitude,
            phone: Array.isArray(branch.phone) ? branch.phone.join(' / ') : branch.phone,
            website: chain.website,
            hasDelivery: chain.hasDelivery,
            hasOnlineOrdering: chain.hasOnlineOrdering,
            workingHours: branch.workingHours,
            isActive: branch.isActive,
          };
          results.push(record);
        } catch (error: any) {
          console.error(`[SupermarketsCollector] Error processing ${branch.nameAr}: ${error.message}`);
        }
      }
    }

    return results;
  }
}
