import { DataSource } from '@egypt/shared-types';

function makeSource(partial: {
  domain: string;
  sourceName: string;
  sourceUrl: string;
  healthEndpoint?: string;
  type: 'api' | 'website' | 'open_data' | 'structured_file' | 'trusted_public';
  priority: 1 | 2 | 3 | 4 | 5 | 6;
  updateFrequency?: string;
  headers?: Record<string, string>;
  rateLimit?: { requestsPerSecond: number; maxConcurrency: number };
}): DataSource {
  return {
    id: `${partial.domain}-${partial.sourceName.replace(/\s+/g, '-').toLowerCase()}`,
    isAvailable: true,
    lastChecked: null,
    authType: 'none' as const,
    rateLimit: partial.rateLimit ? { requests: partial.rateLimit.requestsPerSecond, perMs: 1000 } : { requests: 1, perMs: 1000 },
    url: partial.sourceUrl,
    name: partial.sourceName,
    sourceUrl: partial.sourceUrl,
    sourceName: partial.sourceName,
    domain: partial.domain,
    type: partial.type,
    priority: partial.priority,
    updateFrequency: partial.updateFrequency,
    healthEndpoint: partial.healthEndpoint,
    headers: partial.headers,
  };
}

export const OFFICIAL_SOURCES: DataSource[] = [
  makeSource({
    domain: 'banks',
    sourceName: 'Central Bank of Egypt',
    sourceUrl: 'https://www.cbe.org.eg',
    healthEndpoint: 'https://www.cbe.org.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'banks',
    sourceName: 'Egyptian Banking Institute',
    sourceUrl: 'https://www.ebi.gov.eg',
    healthEndpoint: 'https://www.ebi.gov.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'pharmacies',
    sourceName: 'Egyptian Ministry of Health',
    sourceUrl: 'https://www.mohp.gov.eg',
    healthEndpoint: 'https://www.mohp.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'pharmacies',
    sourceName: 'Egyptian Drug Authority',
    sourceUrl: 'https://www.eda.mohp.gov.eg',
    healthEndpoint: 'https://www.eda.mohp.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'pharmacies',
    sourceName: 'Egyptian Pharmacists Syndicate',
    sourceUrl: 'https://www.eps.com.eg',
    healthEndpoint: 'https://www.eps.com.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'hospitals',
    sourceName: 'Egyptian Ministry of Health - Hospitals',
    sourceUrl: 'https://www.mohp.gov.eg/hospitals',
    healthEndpoint: 'https://www.mohp.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'hospitals',
    sourceName: 'General Authority for Healthcare Accreditation',
    sourceUrl: 'https://www.gahealthcare.eg',
    healthEndpoint: 'https://www.gahealthcare.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'government',
    sourceName: 'Egyptian Government Services Portal',
    sourceUrl: 'https://www.gov.eg',
    healthEndpoint: 'https://www.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'government',
    sourceName: 'Egyptian Cabinet Information Center',
    sourceUrl: 'https://www.idsc.gov.eg',
    healthEndpoint: 'https://www.idsc.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'transport',
    sourceName: 'Ministry of Transport',
    sourceUrl: 'https://www.mot.gov.eg',
    healthEndpoint: 'https://www.mot.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'transport',
    sourceName: 'Cairo Metro - National Authority for Tunnels',
    sourceUrl: 'https://www.nat.gov.eg',
    healthEndpoint: 'https://www.nat.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'transport',
    sourceName: 'Egyptian National Railways',
    sourceUrl: 'https://enr.gov.eg',
    healthEndpoint: 'https://enr.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'emergency',
    sourceName: 'Ministry of Interior',
    sourceUrl: 'https://www.moiegypt.gov.eg',
    healthEndpoint: 'https://www.moiegypt.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'emergency',
    sourceName: 'Egyptian Ambulance Authority',
    sourceUrl: 'https://www.ambulance.eg',
    healthEndpoint: 'https://www.ambulance.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'emergency',
    sourceName: 'Egyptian Red Crescent',
    sourceUrl: 'https://www.egyptianrc.org',
    healthEndpoint: 'https://www.egyptianrc.org',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'banks',
    sourceName: 'National Bank of Egypt',
    sourceUrl: 'https://www.nbe.com.eg',
    healthEndpoint: 'https://www.nbe.com.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'banks',
    sourceName: 'Banque Misr',
    sourceUrl: 'https://www.banquemisr.com',
    healthEndpoint: 'https://www.banquemisr.com',
    type: 'website',
    priority: 3,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'banks',
    sourceName: 'Commercial International Bank',
    sourceUrl: 'https://www.cibeg.com',
    healthEndpoint: 'https://www.cibeg.com',
    type: 'website',
    priority: 3,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'telecom',
    sourceName: 'Orange Egypt',
    sourceUrl: 'https://www.orange.eg',
    healthEndpoint: 'https://www.orange.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'telecom',
    sourceName: 'Vodafone Egypt',
    sourceUrl: 'https://www.vodafone.com.eg',
    healthEndpoint: 'https://www.vodafone.com.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'telecom',
    sourceName: 'Etisalat Egypt',
    sourceUrl: 'https://www.etisalat.eg',
    healthEndpoint: 'https://www.etisalat.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'telecom',
    sourceName: 'Telecom Egypt (WE)',
    sourceUrl: 'https://www.we.eg',
    healthEndpoint: 'https://www.we.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'supermarkets',
    sourceName: 'Carrefour Egypt',
    sourceUrl: 'https://www.carrefouregypt.com',
    healthEndpoint: 'https://www.carrefouregypt.com',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'supermarkets',
    sourceName: 'Metro Market Egypt',
    sourceUrl: 'https://www.metro-market.eg',
    healthEndpoint: 'https://www.metro-market.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'supermarkets',
    sourceName: 'Hyper One',
    sourceUrl: 'https://www.hyperone.com.eg',
    healthEndpoint: 'https://www.hyperone.com.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'supermarkets',
    sourceName: 'Seoudi Market',
    sourceUrl: 'https://www.seoudi.com.eg',
    healthEndpoint: 'https://www.seoudi.com.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'hospitals',
    sourceName: 'Dar El Fouad Hospital',
    sourceUrl: 'https://www.darelfouad.com',
    healthEndpoint: 'https://www.darelfouad.com',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'hospitals',
    sourceName: 'Cleopatra Hospital',
    sourceUrl: 'https://www.cleopatra-hospital.com',
    healthEndpoint: 'https://www.cleopatra-hospital.com',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'pharmacies',
    sourceName: '19011 (El Ezaby)',
    sourceUrl: 'https://www.19011.com',
    healthEndpoint: 'https://www.19011.com',
    type: 'website',
    priority: 2,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'pharmacies',
    sourceName: 'Seif Pharmacy',
    sourceUrl: 'https://www.seifpharmacy.com',
    healthEndpoint: 'https://www.seifpharmacy.com',
    type: 'website',
    priority: 3,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'pharmacies',
    sourceName: 'Ministry of Communications and IT',
    sourceUrl: 'https://www.mcit.gov.eg',
    healthEndpoint: 'https://www.mcit.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'telecom',
    sourceName: 'National Telecom Regulatory Authority',
    sourceUrl: 'https://www.tra.gov.eg',
    healthEndpoint: 'https://www.tra.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'supermarkets',
    sourceName: 'Ministry of Supply and Internal Trade',
    sourceUrl: 'https://www.msit.gov.eg',
    healthEndpoint: 'https://www.msit.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
  makeSource({
    domain: 'supermarkets',
    sourceName: 'Consumer Protection Agency',
    sourceUrl: 'https://www.cpa.gov.eg',
    healthEndpoint: 'https://www.cpa.gov.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  }),
];

export const SOURCE_CONFIGS_BY_DOMAIN: Record<string, DataSource[]> = {};
for (const source of OFFICIAL_SOURCES) {
  if (!SOURCE_CONFIGS_BY_DOMAIN[source.domain]) {
    SOURCE_CONFIGS_BY_DOMAIN[source.domain] = [];
  }
  SOURCE_CONFIGS_BY_DOMAIN[source.domain].push(source);
}

export const DOMAINS = ['banks', 'pharmacies', 'hospitals', 'government', 'transport', 'emergency', 'telecom', 'supermarkets'] as const;
export type Domain = typeof DOMAINS[number];

export function getSourcesForDomain(domain: string): DataSource[] {
  return SOURCE_CONFIGS_BY_DOMAIN[domain] || [];
}

export function getPriorityLabel(priority: number): string {
  const labels: Record<number, string> = {
    1: 'Official Government API',
    2: 'Official Government Website',
    3: 'Open Data Portal',
    4: 'Structured Data Source',
    5: 'Trusted Public Source',
    6: 'Community Contribution',
  };
  return labels[priority] || 'Unknown';
}