import { DataSource } from '@egypt/shared-types';

export const OFFICIAL_SOURCES: DataSource[] = [
  {
    domain: 'banks',
    sourceName: 'Central Bank of Egypt',
    sourceUrl: 'https://www.cbe.org.eg',
    healthEndpoint: 'https://www.cbe.org.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'banks',
    sourceName: 'Egyptian Banking Institute',
    sourceUrl: 'https://www.ebi.gov.eg',
    healthEndpoint: 'https://www.ebi.gov.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'pharmacies',
    sourceName: 'Egyptian Ministry of Health',
    sourceUrl: 'https://www.mohp.gov.eg',
    healthEndpoint: 'https://www.mohp.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'pharmacies',
    sourceName: 'Egyptian Drug Authority',
    sourceUrl: 'https://www.eda.mohp.gov.eg',
    healthEndpoint: 'https://www.eda.mohp.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'pharmacies',
    sourceName: 'Egyptian Pharmacists Syndicate',
    sourceUrl: 'https://www.eps.com.eg',
    healthEndpoint: 'https://www.eps.com.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'hospitals',
    sourceName: 'Egyptian Ministry of Health - Hospitals',
    sourceUrl: 'https://www.mohp.gov.eg/hospitals',
    healthEndpoint: 'https://www.mohp.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'hospitals',
    sourceName: 'General Authority for Healthcare Accreditation',
    sourceUrl: 'https://www.gahealthcare.eg',
    healthEndpoint: 'https://www.gahealthcare.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'government',
    sourceName: 'Egyptian Government Services Portal',
    sourceUrl: 'https://www.gov.eg',
    healthEndpoint: 'https://www.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'weekly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'government',
    sourceName: 'Egyptian Cabinet Information Center',
    sourceUrl: 'https://www.idsc.gov.eg',
    healthEndpoint: 'https://www.idsc.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'transport',
    sourceName: 'Ministry of Transport',
    sourceUrl: 'https://www.mot.gov.eg',
    healthEndpoint: 'https://www.mot.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'transport',
    sourceName: 'Cairo Metro - National Authority for Tunnels',
    sourceUrl: 'https://www.nat.gov.eg',
    healthEndpoint: 'https://www.nat.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'transport',
    sourceName: 'Egyptian National Railways',
    sourceUrl: 'https://enr.gov.eg',
    healthEndpoint: 'https://enr.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'emergency',
    sourceName: 'Ministry of Interior',
    sourceUrl: 'https://www.moiegypt.gov.eg',
    healthEndpoint: 'https://www.moiegypt.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'emergency',
    sourceName: 'Egyptian Ambulance Authority',
    sourceUrl: 'https://www.ambulance.eg',
    healthEndpoint: 'https://www.ambulance.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'emergency',
    sourceName: 'Egyptian Red Crescent',
    sourceUrl: 'https://www.egyptianrc.org',
    healthEndpoint: 'https://www.egyptianrc.org',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'telecom',
    sourceName: 'Ministry of Communications and IT',
    sourceUrl: 'https://www.mcit.gov.eg',
    healthEndpoint: 'https://www.mcit.gov.eg',
    type: 'website',
    priority: 1,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'telecom',
    sourceName: 'National Telecom Regulatory Authority',
    sourceUrl: 'https://www.tra.gov.eg',
    healthEndpoint: 'https://www.tra.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 2, maxConcurrency: 1 },
  },
  {
    domain: 'supermarkets',
    sourceName: 'Ministry of Supply and Internal Trade',
    sourceUrl: 'https://www.msit.gov.eg',
    healthEndpoint: 'https://www.msit.gov.eg',
    type: 'website',
    priority: 2,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
  {
    domain: 'supermarkets',
    sourceName: 'Consumer Protection Agency',
    sourceUrl: 'https://www.cpa.gov.eg',
    healthEndpoint: 'https://www.cpa.gov.eg',
    type: 'website',
    priority: 3,
    updateFrequency: 'monthly',
    headers: { 'User-Agent': 'EgyptServicesPlatform/1.0', 'Accept-Language': 'ar-EG' },
    rateLimit: { requestsPerSecond: 1, maxConcurrency: 1 },
  },
];

export const SOURCE_CONFIGS_BY_DOMAIN: Record<string, DataSource[]> = {};
for (const source of OFFICIAL_SOURCES) {
  if (!SOURCE_CONFIGS_BY_DOMAIN[source.domain]) {
    SOURCE_CONFIGS_BY_DOMAIN[source.domain] = [];
  }
  SOURCE_CONFIGS_BY_DOMAIN[source.domain].push(source);
}

export const DOMAINS = ['banks', 'pharmacies', 'hospitals', 'government', 'transport', 'emergency', 'telecom', 'supermarkets'] as const;
export type Domain = typeof DOMAINS[number];

export function getSourcesForDomain(domain: string): DataSource[] {
  return SOURCE_CONFIGS_BY_DOMAIN[domain] || [];
}

export function getPriorityLabel(priority: number): string {
  const labels: Record<number, string> = {
    1: 'Official Government API',
    2: 'Official Government Website',
    3: 'Open Data Portal',
    4: 'Structured Data Source',
    5: 'Trusted Public Source',
    6: 'Community Contribution',
  };
  return labels[priority] || 'Unknown';
}